"""Compatibility aliases for normal search.

The canonical normal Job search endpoint is now `GET /api/job/search`.
These aliases keep the existing frontend/test surface (`/api/jobs`, `/api/cvs`,
`/api/candidates`) stable while routing to normal PostgreSQL Job/CV tables.
They do not read V2 prototype tables.
"""

from __future__ import annotations

from datetime import datetime
from typing import Annotated

import psycopg
from fastapi import APIRouter, Depends, Query

from routers.auth import get_db_connection
from routers.cv_router import search_cvs_response
from routers.job_router import search_jobs_response
from schemas.normal_cv_schema import CVSearchListResponse
from schemas.normal_job_schema import JobSearchListResponse


router = APIRouter(tags=["normal-search"])
DbConnection = Annotated[psycopg.Connection, Depends(get_db_connection)]


@router.get("/jobs", response_model=JobSearchListResponse)
def search_jobs_alias(
    conn: DbConnection,
    q: str | None = Query(default=None, max_length=200),
    keyword: str | None = Query(default=None, max_length=200),
    title: str | None = None,
    company_name: str | None = None,
    company_industry: str | None = None,
    industry: str | None = None,
    occupationGroup: str | None = None,
    occupation_group: str | None = None,
    status_value: str | None = Query(default=None, alias="status"),
    visibility: str | None = None,
    category: str | None = None,
    department: str | None = None,
    location_city: str | None = Query(default=None, alias="location.city"),
    location: str | None = None,
    location_country: str | None = Query(default=None, alias="location.country"),
    remote: bool | None = None,
    remote_type: str | None = None,
    workingModel: str | None = None,
    employmentType: str | None = None,
    employment_type: str | None = None,
    seniority: str | None = None,
    experienceLevel: str | None = None,
    experienceYearsMin: float | None = Query(default=None, ge=0),
    experienceYearsMax: float | None = Query(default=None, ge=0),
    educationLevel: str | None = None,
    skills: str | None = None,
    mustHaveSkills: str | None = None,
    niceToHaveSkills: str | None = None,
    toolsAndTechnologies: str | None = None,
    domainKnowledge: str | None = None,
    categories: str | None = None,
    tags: str | None = None,
    salaryMin: float | None = Query(default=None, ge=0),
    salaryMax: float | None = Query(default=None, ge=0),
    salary_min: float | None = Query(default=None, ge=0),
    salary_max: float | None = Query(default=None, ge=0),
    salary_currency: str | None = Query(default=None, alias="salary.currency"),
    salary_period: str | None = Query(default=None, alias="salary.period"),
    archived: bool | None = None,
    applicationDeadlineFrom: datetime | None = None,
    applicationDeadlineTo: datetime | None = None,
    page: int = Query(default=1, ge=1),
    limit: int = Query(default=10, ge=1, le=50),
    sort: str | None = "newest",
) -> JobSearchListResponse:
    return search_jobs_response(
        conn,
        keyword=keyword,
        q=q,
        title=title,
        company_name=company_name,
        company_industry=company_industry,
        industry=industry,
        occupation_group=occupationGroup or occupation_group,
        status_filter=status_value,
        visibility=visibility,
        category=category,
        department=department,
        location_city=location_city,
        location=location,
        location_country=location_country,
        remote=remote,
        remote_type=remote_type,
        working_model=workingModel,
        employment_type=employmentType or employment_type,
        seniority=seniority or experienceLevel,
        experience_years_min=experienceYearsMin,
        experience_years_max=experienceYearsMax,
        education_level=educationLevel,
        skills=skills,
        must_have_skills=mustHaveSkills,
        nice_to_have_skills=niceToHaveSkills,
        tools_and_technologies=toolsAndTechnologies,
        domain_knowledge=domainKnowledge,
        categories=categories,
        tags=tags,
        salary_min=salaryMin if salaryMin is not None else salary_min,
        salary_max=salaryMax if salaryMax is not None else salary_max,
        salary_currency=salary_currency,
        salary_period=salary_period,
        archived=archived,
        application_deadline_from=applicationDeadlineFrom,
        application_deadline_to=applicationDeadlineTo,
        page=page,
        limit=limit,
        sort=sort,
    )


@router.get("/cvs", response_model=CVSearchListResponse)
def search_cvs_alias(
    conn: DbConnection,
    q: str | None = Query(default=None, max_length=200),
    keyword: str | None = Query(default=None, max_length=200),
    fullname: str | None = None,
    headline: str | None = None,
    target_role: str | None = None,
    targetRole: str | None = None,
    city: str | None = None,
    location_city: str | None = Query(default=None, alias="location.city"),
    location: str | None = None,
    country: str | None = None,
    locationCountry: str | None = None,
    location_country: str | None = Query(default=None, alias="location.country"),
    desiredIndustry: str | None = None,
    industry: str | None = None,
    occupationGroup: str | None = None,
    occupation_group: str | None = None,
    status_value: str | None = Query(default=None, alias="status"),
    careerLevel: str | None = None,
    experienceLevel: str | None = None,
    yearsOfExperienceMin: float | None = Query(default=None, ge=0),
    yearsOfExperienceMax: float | None = Query(default=None, ge=0),
    educationLevel: str | None = None,
    education_level_alias: str | None = Query(default=None, alias="education.level"),
    educationMajor: str | None = None,
    education_major: str | None = Query(default=None, alias="education.major"),
    workingModel: str | None = None,
    employmentType: str | None = None,
    employment_type: str | None = None,
    availability: str | None = None,
    skills: str | None = None,
    toolsAndTechnologies: str | None = None,
    domainKnowledge: str | None = None,
    certifications: str | None = None,
    certification_name_alias: str | None = Query(default=None, alias="certifications.name"),
    certificationName: str | None = None,
    language_name_alias: str | None = Query(default=None, alias="languages.name"),
    languageName: str | None = None,
    language_level_alias: str | None = Query(default=None, alias="languages.level"),
    languageLevel: str | None = None,
    tags: str | None = None,
    page: int = Query(default=1, ge=1),
    limit: int = Query(default=10, ge=1, le=50),
    sort: str | None = "newest",
) -> CVSearchListResponse:
    return search_cvs_response(
        conn,
        q=q,
        keyword=keyword,
        fullname=fullname,
        headline=headline,
        target_role=target_role,
        targetRole=targetRole,
        location_city=location_city or city,
        location=location,
        location_country=location_country or locationCountry or country,
        desiredIndustry=desiredIndustry or industry,
        occupation_group=occupationGroup or occupation_group,
        status_filter=status_value,
        experienceLevel=careerLevel or experienceLevel,
        years_of_experience_min=yearsOfExperienceMin,
        years_of_experience_max=yearsOfExperienceMax,
        educationLevel=educationLevel or education_level_alias,
        education_major=education_major or educationMajor,
        workingModel=workingModel,
        employmentType=employmentType,
        employment_type=employment_type,
        availability=availability,
        skills=skills,
        tools_and_technologies=toolsAndTechnologies,
        domain_knowledge=domainKnowledge,
        certification_name=certificationName or certification_name_alias or certifications,
        language_name=languageName or language_name_alias,
        language_level=languageLevel or language_level_alias,
        tags=tags,
        page=page,
        limit=limit,
        sort=sort,
    )


@router.get("/candidates", response_model=CVSearchListResponse)
def search_candidates_alias(
    conn: DbConnection,
    q: str | None = Query(default=None, max_length=200),
    keyword: str | None = Query(default=None, max_length=200),
    fullname: str | None = None,
    headline: str | None = None,
    target_role: str | None = None,
    targetRole: str | None = None,
    city: str | None = None,
    location_city: str | None = Query(default=None, alias="location.city"),
    location: str | None = None,
    country: str | None = None,
    locationCountry: str | None = None,
    location_country: str | None = Query(default=None, alias="location.country"),
    desiredIndustry: str | None = None,
    industry: str | None = None,
    occupationGroup: str | None = None,
    occupation_group: str | None = None,
    status_value: str | None = Query(default=None, alias="status"),
    careerLevel: str | None = None,
    experienceLevel: str | None = None,
    yearsOfExperienceMin: float | None = Query(default=None, ge=0),
    yearsOfExperienceMax: float | None = Query(default=None, ge=0),
    educationLevel: str | None = None,
    education_level_alias: str | None = Query(default=None, alias="education.level"),
    educationMajor: str | None = None,
    education_major: str | None = Query(default=None, alias="education.major"),
    workingModel: str | None = None,
    employmentType: str | None = None,
    employment_type: str | None = None,
    availability: str | None = None,
    skills: str | None = None,
    toolsAndTechnologies: str | None = None,
    domainKnowledge: str | None = None,
    certifications: str | None = None,
    certification_name_alias: str | None = Query(default=None, alias="certifications.name"),
    certificationName: str | None = None,
    language_name_alias: str | None = Query(default=None, alias="languages.name"),
    languageName: str | None = None,
    language_level_alias: str | None = Query(default=None, alias="languages.level"),
    languageLevel: str | None = None,
    tags: str | None = None,
    page: int = Query(default=1, ge=1),
    limit: int = Query(default=10, ge=1, le=50),
    sort: str | None = "newest",
) -> CVSearchListResponse:
    return search_cvs_response(
        conn,
        q=q,
        keyword=keyword,
        fullname=fullname,
        headline=headline,
        target_role=target_role,
        targetRole=targetRole,
        location_city=location_city or city,
        location=location,
        location_country=location_country or locationCountry or country,
        desiredIndustry=desiredIndustry or industry,
        occupation_group=occupationGroup or occupation_group,
        status_filter=status_value,
        experienceLevel=careerLevel or experienceLevel,
        years_of_experience_min=yearsOfExperienceMin,
        years_of_experience_max=yearsOfExperienceMax,
        educationLevel=educationLevel or education_level_alias,
        education_major=education_major or educationMajor,
        workingModel=workingModel,
        employmentType=employmentType,
        employment_type=employment_type,
        availability=availability,
        skills=skills,
        tools_and_technologies=toolsAndTechnologies,
        domain_knowledge=domainKnowledge,
        certification_name=certificationName or certification_name_alias or certifications,
        language_name=languageName or language_name_alias,
        language_level=languageLevel or language_level_alias,
        tags=tags,
        page=page,
        limit=limit,
        sort=sort,
    )
