CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS users (
    user_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email          VARCHAR(320) NOT NULL UNIQUE,
    password_hash  TEXT NOT NULL,
    role           VARCHAR(32) NOT NULL,
    status         VARCHAR(32) NOT NULL DEFAULT 'active',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT users_role_chk CHECK (role IN ('candidate', 'recruiter', 'admin')),
    CONSTRAINT users_status_chk CHECK (status IN ('active', 'invited', 'disabled'))
);

CREATE TABLE IF NOT EXISTS organizations (
    organization_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    slug            VARCHAR(255) UNIQUE,
    logo_url        TEXT,
    about           TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS recruiter_profiles (
    user_id          BIGINT PRIMARY KEY REFERENCES users(user_id),
    organization_id BIGINT NOT NULL REFERENCES organizations(organization_id),
    full_name       VARCHAR(255) NOT NULL,
    title           VARCHAR(255),
    phone           VARCHAR(64),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS candidate_profiles (
    user_id                BIGINT PRIMARY KEY REFERENCES users(user_id),
    full_name              VARCHAR(255) NOT NULL,
    phone                  VARCHAR(64),
    current_location       VARCHAR(64),
    total_experience_years INTEGER,
    headline               VARCHAR(255),
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT candidate_profiles_current_location_chk
        CHECK (current_location IS NULL OR current_location IN ('ha_noi', 'tp_hcm', 'da_nang')),
    CONSTRAINT candidate_profiles_total_experience_chk
        CHECK (total_experience_years IS NULL OR total_experience_years >= 0)
);

CREATE TABLE IF NOT EXISTS candidate_resumes (
    resume_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_user_id BIGINT NOT NULL REFERENCES users(user_id),
    title             TEXT NOT NULL,
    summary           TEXT NOT NULL DEFAULT '',
    experience        TEXT NOT NULL DEFAULT '',
    skills            TEXT[] NOT NULL DEFAULT '{}',
    location          VARCHAR(64) NOT NULL,
    job_type          VARCHAR(64) NOT NULL,
    seniority         VARCHAR(64) NOT NULL,
    education         VARCHAR(64) NOT NULL,
    certifications    TEXT[] NOT NULL DEFAULT '{}',
    is_primary        BOOLEAN NOT NULL DEFAULT false,
    status            VARCHAR(32) NOT NULL DEFAULT 'draft',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT candidate_resumes_status_chk CHECK (status IN ('draft', 'active', 'archived')),
    CONSTRAINT candidate_resumes_location_chk CHECK (location IN ('ha_noi', 'tp_hcm', 'da_nang')),
    CONSTRAINT candidate_resumes_job_type_chk CHECK (job_type IN ('remote', 'fulltime', 'parttime')),
    CONSTRAINT candidate_resumes_seniority_chk CHECK (seniority IN ('intern', 'fresher', 'junior', 'mid', 'senior', 'lead')),
    CONSTRAINT candidate_resumes_education_chk CHECK (education IN ('lop_9', 'lop_12', 'dai_hoc', 'thac_si', 'tien_si'))
);

CREATE TABLE IF NOT EXISTS job_posts (
    job_id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id         BIGINT NOT NULL REFERENCES organizations(organization_id),
    recruiter_user_id       BIGINT NOT NULL REFERENCES users(user_id),
    title                   TEXT NOT NULL,
    requirement             TEXT NOT NULL DEFAULT '',
    skills                  TEXT[] NOT NULL DEFAULT '{}',
    location                VARCHAR(64) NOT NULL,
    job_type                VARCHAR(64) NOT NULL,
    seniority               VARCHAR(64) NOT NULL,
    education               VARCHAR(64) NOT NULL,
    required_certifications TEXT[] NOT NULL DEFAULT '{}',
    status                  VARCHAR(32) NOT NULL DEFAULT 'draft',
    published_at            TIMESTAMPTZ,
    expires_at              TIMESTAMPTZ,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT job_posts_status_chk CHECK (status IN ('draft', 'published', 'closed')),
    CONSTRAINT job_posts_location_chk CHECK (location IN ('ha_noi', 'tp_hcm', 'da_nang')),
    CONSTRAINT job_posts_job_type_chk CHECK (job_type IN ('remote', 'fulltime', 'parttime')),
    CONSTRAINT job_posts_seniority_chk CHECK (seniority IN ('intern', 'fresher', 'junior', 'mid', 'senior', 'lead')),
    CONSTRAINT job_posts_education_chk CHECK (education IN ('lop_9', 'lop_12', 'dai_hoc', 'thac_si', 'tien_si')),
    CONSTRAINT job_posts_expires_after_publish_chk
        CHECK (expires_at IS NULL OR published_at IS NULL OR expires_at > published_at)
);

CREATE TABLE IF NOT EXISTS candidate_resume_embeddings (
    resume_id         BIGINT PRIMARY KEY REFERENCES candidate_resumes(resume_id) ON DELETE CASCADE,
    emb_title         VECTOR(384),
    emb_skills        VECTOR(384),
    emb_summary       VECTOR(384),
    emb_experience    VECTOR(384),
    embedding_version VARCHAR(128) NOT NULL,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS job_post_embeddings (
    job_id            BIGINT PRIMARY KEY REFERENCES job_posts(job_id) ON DELETE CASCADE,
    emb_title         VECTOR(384),
    emb_skills        VECTOR(384),
    emb_requirement   VECTOR(384),
    embedding_version VARCHAR(128) NOT NULL,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS uploaded_documents (
    document_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id     BIGINT NOT NULL REFERENCES users(user_id),
    document_type     VARCHAR(64) NOT NULL,
    object_key        TEXT,
    file_url          TEXT,
    original_filename TEXT NOT NULL,
    mime_type         VARCHAR(255) NOT NULL,
    file_size_bytes   BIGINT NOT NULL,
    resume_id         BIGINT REFERENCES candidate_resumes(resume_id),
    job_id            BIGINT REFERENCES job_posts(job_id),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uploaded_documents_type_chk CHECK (document_type IN ('candidate_resume', 'job_post')),
    CONSTRAINT uploaded_documents_storage_ref_chk CHECK (object_key IS NOT NULL OR file_url IS NOT NULL),
    CONSTRAINT uploaded_documents_size_chk CHECK (file_size_bytes > 0)
);

CREATE TABLE IF NOT EXISTS parse_jobs (
    parse_job_id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id                 BIGINT NOT NULL REFERENCES uploaded_documents(document_id),
    target_entity_type          VARCHAR(64) NOT NULL,
    resume_id                   BIGINT REFERENCES candidate_resumes(resume_id),
    job_id                      BIGINT REFERENCES job_posts(job_id),
    status                      VARCHAR(32) NOT NULL DEFAULT 'queued',
    extracted_text              TEXT,
    extracted_text_object_key   TEXT,
    parser_version              VARCHAR(128) NOT NULL,
    embedding_version_requested VARCHAR(128) NOT NULL,
    error_code                  VARCHAR(128),
    error_message               TEXT,
    started_at                  TIMESTAMPTZ,
    finished_at                 TIMESTAMPTZ,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT parse_jobs_target_type_chk CHECK (target_entity_type IN ('candidate_resume', 'job_post')),
    CONSTRAINT parse_jobs_status_chk CHECK (status IN ('queued', 'processing', 'succeeded', 'failed'))
);

CREATE TABLE IF NOT EXISTS applications (
    application_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id            BIGINT NOT NULL REFERENCES job_posts(job_id),
    candidate_user_id BIGINT NOT NULL REFERENCES users(user_id),
    resume_id         BIGINT NOT NULL REFERENCES candidate_resumes(resume_id),
    status            VARCHAR(32) NOT NULL DEFAULT 'submitted',
    applied_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT applications_status_chk CHECK (status IN ('submitted', 'shortlisted', 'rejected', 'hired', 'withdrawn')),
    CONSTRAINT applications_job_resume_uniq UNIQUE (job_id, resume_id)
);

CREATE TABLE IF NOT EXISTS application_events (
    event_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    application_id BIGINT NOT NULL REFERENCES applications(application_id) ON DELETE CASCADE,
    from_status    VARCHAR(32),
    to_status      VARCHAR(32) NOT NULL,
    actor_user_id  BIGINT REFERENCES users(user_id),
    note           TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS recruiter_invites (
    invite_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id            BIGINT NOT NULL REFERENCES job_posts(job_id),
    resume_id         BIGINT NOT NULL REFERENCES candidate_resumes(resume_id),
    candidate_user_id BIGINT NOT NULL REFERENCES users(user_id),
    recruiter_user_id BIGINT NOT NULL REFERENCES users(user_id),
    status            VARCHAR(32) NOT NULL DEFAULT 'pending',
    message           TEXT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT recruiter_invites_status_chk CHECK (status IN ('pending', 'accepted', 'rejected'))
);

CREATE TABLE IF NOT EXISTS notifications (
    notification_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id     BIGINT NOT NULL REFERENCES users(user_id),
    type                  VARCHAR(128) NOT NULL,
    status                VARCHAR(32) NOT NULL DEFAULT 'unread',
    title                 TEXT NOT NULL,
    body                  TEXT NOT NULL,
    entity_type           VARCHAR(64),
    entity_id             BIGINT,
    email_delivery_status VARCHAR(64),
    metadata              JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT notifications_status_chk CHECK (status IN ('unread', 'read'))
);

ALTER TABLE IF EXISTS notifications
    ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE TABLE IF NOT EXISTS email_attempts (
    email_attempt_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_email  VARCHAR(320),
    recipient_user_id BIGINT REFERENCES users(user_id),
    subject          TEXT NOT NULL,
    body_preview     TEXT NOT NULL DEFAULT '',
    event_type       VARCHAR(128) NOT NULL,
    status           VARCHAR(32) NOT NULL,
    provider         VARCHAR(128) NOT NULL,
    error_message    TEXT,
    entity_type      VARCHAR(64),
    entity_id        BIGINT,
    metadata         JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT email_attempts_status_chk CHECK (status IN ('logged', 'sent', 'failed'))
);

CREATE TABLE IF NOT EXISTS audit_logs (
    audit_log_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id      BIGINT REFERENCES users(user_id),
    event_type         VARCHAR(128) NOT NULL,
    target_entity_type VARCHAR(64) NOT NULL,
    target_entity_id   BIGINT,
    metadata           JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS candidate_resumes_public_pool_idx
    ON candidate_resumes (status, location, job_type, seniority, education)
    WHERE status = 'active';
CREATE INDEX IF NOT EXISTS job_posts_public_pool_idx
    ON job_posts (status, location, job_type, seniority, education)
    WHERE status = 'published';
CREATE INDEX IF NOT EXISTS applications_job_status_idx ON applications (job_id, status);
CREATE INDEX IF NOT EXISTS recruiter_invites_candidate_status_idx
    ON recruiter_invites (candidate_user_id, status);
CREATE INDEX IF NOT EXISTS notifications_recipient_status_created_idx
    ON notifications (recipient_user_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS email_attempts_event_created_idx
    ON email_attempts (event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS email_attempts_entity_idx
    ON email_attempts (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS audit_logs_event_created_idx
    ON audit_logs (event_type, created_at DESC);
