-- Matching V2 Slice 6C broad ranking seed extension.
-- Adds deterministic pass/noisy candidates for the default 10 JD SQL seed.
-- Scope: prototype JD/CV/embedding tables only. No match_results_v2.

INSERT INTO candidate_profiles_v2
    (cv_id, title, skills, summary, experience, location, job_type, seniority, education, certifications)
VALUES
    (1101, 'Junior Backend Engineer',
     ARRAY['python', 'fastapi'],
     'Junior backend engineer focused on Python API delivery.',
     'Built FastAPI services with database-backed CRUD workflows.',
     'Hà Nội', 'fulltime', 'junior', 'bachelor', ARRAY[]::TEXT[]),
    (1102, 'Junior Python API Developer',
     ARRAY['python', 'postgresql'],
     'Junior API developer with Python and PostgreSQL project experience.',
     'Implemented service endpoints and SQL-backed reporting features.',
     'Hà Nội', 'fulltime', 'junior', 'bachelor', ARRAY[]::TEXT[]),
    (1103, 'Junior Support Developer',
     ARRAY['html', 'support'],
     'Entry-level developer with support tooling background.',
     'Maintained internal tools and handled production support tickets.',
     'Hà Nội', 'fulltime', 'junior', 'bachelor', ARRAY[]::TEXT[]),

    (1111, 'Junior Frontend Engineer',
     ARRAY['react', 'typescript'],
     'Frontend engineer building typed React interfaces.',
     'Delivered React and TypeScript pages for customer dashboards.',
     'TP. Hồ Chí Minh', 'fulltime', 'junior', 'bachelor', ARRAY[]::TEXT[]),
    (1112, 'Junior React Developer',
     ARRAY['react', 'css'],
     'React developer with component and styling experience.',
     'Built reusable UI components and CSS layouts.',
     'TP. Hồ Chí Minh', 'fulltime', 'junior', 'bachelor', ARRAY[]::TEXT[]),
    (1113, 'Junior Customer Tools Specialist',
     ARRAY['crm', 'support'],
     'Junior specialist maintaining customer support tooling.',
     'Configured CRM workflows and internal support forms.',
     'TP. Hồ Chí Minh', 'fulltime', 'junior', 'bachelor', ARRAY[]::TEXT[]),

    (1121, 'Senior Fullstack Engineer',
     ARRAY['python', 'react', 'postgresql'],
     'Senior fullstack engineer owning Python services and React UIs.',
     'Led end-to-end delivery across backend APIs, React frontends, and PostgreSQL.',
     'Đà Nẵng', 'remote', 'senior', 'bachelor', ARRAY[]::TEXT[]),
    (1122, 'Senior Product Platform Engineer',
     ARRAY['python', 'react', 'docker'],
     'Senior engineer across application platforms and deployment workflows.',
     'Built Python APIs, React tools, and Docker-based delivery pipelines.',
     'TP. Hồ Chí Minh', 'remote', 'senior', 'bachelor', ARRAY[]::TEXT[]),
    (1123, 'Senior Cloud Operations Engineer',
     ARRAY['linux', 'monitoring'],
     'Senior remote engineer focused on operations and monitoring.',
     'Ran monitoring and Linux operations for distributed services.',
     'Hà Nội', 'remote', 'senior', 'bachelor', ARRAY[]::TEXT[]),

    (1131, 'Lead Data Engineer',
     ARRAY['python', 'spark', 'sql'],
     'Lead data engineer owning Spark and warehouse pipelines.',
     'Led data platform delivery using Python, Spark, and SQL warehouses.',
     'Hà Nội', 'fulltime', 'lead', 'master', ARRAY['databricks_de']),
    (1133, 'Lead Operations Analyst',
     ARRAY['excel', 'operations'],
     'Lead analyst with operations reporting background.',
     'Managed spreadsheet-heavy operations reports and stakeholder follow-up.',
     'Hà Nội', 'fulltime', 'lead', 'master', ARRAY['databricks_de']),

    (1141, 'Mid Java Backend Developer',
     ARRAY['java', 'spring'],
     'Part-time Java backend developer for Spring services.',
     'Maintained Spring Boot services and Java integrations.',
     'Đà Nẵng', 'parttime', 'mid', 'high_school', ARRAY[]::TEXT[]),
    (1143, 'Mid Admin Support Specialist',
     ARRAY['admin', 'support'],
     'Part-time operations support profile with light technical work.',
     'Handled admin processes and support queues for branch operations.',
     'Đà Nẵng', 'parttime', 'mid', 'bachelor', ARRAY[]::TEXT[]),

    (1152, 'Senior DevOps Platform Engineer',
     ARRAY['docker', 'kubernetes', 'linux'],
     'Senior DevOps engineer with container platform experience.',
     'Operated Kubernetes clusters and Docker-based deployment workflows.',
     'TP. Hồ Chí Minh', 'remote', 'senior', 'bachelor', ARRAY['cka', 'aws_saa']),
    (1153, 'Senior Infrastructure Support Engineer',
     ARRAY['linux', 'monitoring'],
     'Senior infrastructure support engineer with monitoring ownership.',
     'Maintained Linux hosts, monitoring checks, and operational runbooks.',
     'Đà Nẵng', 'remote', 'senior', 'bachelor', ARRAY['cka']),

    (1161, 'Mid ML Engineer',
     ARRAY['python', 'tensorflow', 'ml'],
     'Mid ML engineer building TensorFlow model pipelines.',
     'Implemented Python training pipelines and ML model evaluation jobs.',
     'TP. Hồ Chí Minh', 'fulltime', 'mid', 'bachelor', ARRAY[]::TEXT[]),
    (1163, 'Mid Analytics Specialist',
     ARRAY['sql', 'analytics'],
     'Analytics specialist adjacent to data science teams.',
     'Prepared SQL reports and analytics summaries for business teams.',
     'TP. Hồ Chí Minh', 'fulltime', 'mid', 'bachelor', ARRAY[]::TEXT[]),

    (1172, 'Frontend Lead',
     ARRAY['react', 'typescript', 'css'],
     'Frontend lead for React and TypeScript delivery.',
     'Mentored frontend engineers and maintained component systems.',
     'Hà Nội', 'fulltime', 'lead', 'bachelor', ARRAY[]::TEXT[]),
    (1173, 'Lead Web Content Specialist',
     ARRAY['html', 'css'],
     'Lead content specialist with web publishing background.',
     'Managed HTML and CSS content updates for marketing pages.',
     'Hà Nội', 'fulltime', 'lead', 'bachelor', ARRAY[]::TEXT[]),

    (1182, 'Intern Python Developer',
     ARRAY['python'],
     'Intern developer with Python coursework and API practice.',
     'Built small Python services and SQL exercises during internship.',
     'Hà Nội', 'fulltime', 'intern', 'high_school', ARRAY[]::TEXT[]),
    (1183, 'Intern Web Assistant',
     ARRAY['html', 'support'],
     'Intern assistant supporting web and admin tasks.',
     'Helped with HTML updates and internal support tickets.',
     'Hà Nội', 'fulltime', 'intern', 'high_school', ARRAY[]::TEXT[]),

    (1191, 'Mid Data Scientist',
     ARRAY['python', 'ml', 'statistics'],
     'Mid data scientist applying ML and statistics to product analytics.',
     'Built Python models, statistical analyses, and product experiment reports.',
     'Đà Nẵng', 'parttime', 'mid', 'phd', ARRAY['google_ml']),
    (1192, 'Mid Product Data Analyst',
     ARRAY['python', 'statistics', 'sql'],
     'Data analyst using Python and statistics for product insights.',
     'Ran statistical analysis and SQL exploration for analytics teams.',
     'Đà Nẵng', 'parttime', 'mid', 'master', ARRAY['google_ml']),
    (1193, 'Mid Part-time Reporting Analyst',
     ARRAY['excel', 'customer_support'],
     'Reporting analyst with support and spreadsheet-heavy workflows.',
     'Prepared recurring operational reports and support trend analysis.',
     'Đà Nẵng', 'parttime', 'mid', 'master', ARRAY['google_ml']);

INSERT INTO candidate_embeddings_v2
    (cv_id, emb_title, emb_skills, emb_summary, emb_experience)
VALUES
    (1101, array_fill(0.101::real, ARRAY[384])::vector, array_fill(0.102::real, ARRAY[384])::vector, array_fill(0.103::real, ARRAY[384])::vector, array_fill(0.104::real, ARRAY[384])::vector),
    (1102, array_fill(0.105::real, ARRAY[384])::vector, array_fill(0.106::real, ARRAY[384])::vector, array_fill(0.107::real, ARRAY[384])::vector, array_fill(0.108::real, ARRAY[384])::vector),
    (1103, array_fill(0.109::real, ARRAY[384])::vector, array_fill(0.110::real, ARRAY[384])::vector, array_fill(0.111::real, ARRAY[384])::vector, array_fill(0.112::real, ARRAY[384])::vector),
    (1111, array_fill(0.113::real, ARRAY[384])::vector, array_fill(0.114::real, ARRAY[384])::vector, array_fill(0.115::real, ARRAY[384])::vector, array_fill(0.116::real, ARRAY[384])::vector),
    (1112, array_fill(0.117::real, ARRAY[384])::vector, array_fill(0.118::real, ARRAY[384])::vector, array_fill(0.119::real, ARRAY[384])::vector, array_fill(0.120::real, ARRAY[384])::vector),
    (1113, array_fill(0.121::real, ARRAY[384])::vector, array_fill(0.122::real, ARRAY[384])::vector, array_fill(0.123::real, ARRAY[384])::vector, array_fill(0.124::real, ARRAY[384])::vector),
    (1121, array_fill(0.125::real, ARRAY[384])::vector, array_fill(0.126::real, ARRAY[384])::vector, array_fill(0.127::real, ARRAY[384])::vector, array_fill(0.128::real, ARRAY[384])::vector),
    (1122, array_fill(0.129::real, ARRAY[384])::vector, array_fill(0.130::real, ARRAY[384])::vector, array_fill(0.131::real, ARRAY[384])::vector, array_fill(0.132::real, ARRAY[384])::vector),
    (1123, array_fill(0.133::real, ARRAY[384])::vector, array_fill(0.134::real, ARRAY[384])::vector, array_fill(0.135::real, ARRAY[384])::vector, array_fill(0.136::real, ARRAY[384])::vector),
    (1131, array_fill(0.137::real, ARRAY[384])::vector, array_fill(0.138::real, ARRAY[384])::vector, array_fill(0.139::real, ARRAY[384])::vector, array_fill(0.140::real, ARRAY[384])::vector),
    (1133, array_fill(0.141::real, ARRAY[384])::vector, array_fill(0.142::real, ARRAY[384])::vector, array_fill(0.143::real, ARRAY[384])::vector, array_fill(0.144::real, ARRAY[384])::vector),
    (1141, array_fill(0.145::real, ARRAY[384])::vector, array_fill(0.146::real, ARRAY[384])::vector, array_fill(0.147::real, ARRAY[384])::vector, array_fill(0.148::real, ARRAY[384])::vector),
    (1143, array_fill(0.149::real, ARRAY[384])::vector, array_fill(0.150::real, ARRAY[384])::vector, array_fill(0.151::real, ARRAY[384])::vector, array_fill(0.152::real, ARRAY[384])::vector),
    (1152, array_fill(0.153::real, ARRAY[384])::vector, array_fill(0.154::real, ARRAY[384])::vector, array_fill(0.155::real, ARRAY[384])::vector, array_fill(0.156::real, ARRAY[384])::vector),
    (1153, array_fill(0.157::real, ARRAY[384])::vector, array_fill(0.158::real, ARRAY[384])::vector, array_fill(0.159::real, ARRAY[384])::vector, array_fill(0.160::real, ARRAY[384])::vector),
    (1161, array_fill(0.161::real, ARRAY[384])::vector, array_fill(0.162::real, ARRAY[384])::vector, array_fill(0.163::real, ARRAY[384])::vector, array_fill(0.164::real, ARRAY[384])::vector),
    (1163, array_fill(0.165::real, ARRAY[384])::vector, array_fill(0.166::real, ARRAY[384])::vector, array_fill(0.167::real, ARRAY[384])::vector, array_fill(0.168::real, ARRAY[384])::vector),
    (1172, array_fill(0.169::real, ARRAY[384])::vector, array_fill(0.170::real, ARRAY[384])::vector, array_fill(0.171::real, ARRAY[384])::vector, array_fill(0.172::real, ARRAY[384])::vector),
    (1173, array_fill(0.173::real, ARRAY[384])::vector, array_fill(0.174::real, ARRAY[384])::vector, array_fill(0.175::real, ARRAY[384])::vector, array_fill(0.176::real, ARRAY[384])::vector),
    (1182, array_fill(0.177::real, ARRAY[384])::vector, array_fill(0.178::real, ARRAY[384])::vector, array_fill(0.179::real, ARRAY[384])::vector, array_fill(0.180::real, ARRAY[384])::vector),
    (1183, array_fill(0.181::real, ARRAY[384])::vector, array_fill(0.182::real, ARRAY[384])::vector, array_fill(0.183::real, ARRAY[384])::vector, array_fill(0.184::real, ARRAY[384])::vector),
    (1191, array_fill(0.185::real, ARRAY[384])::vector, array_fill(0.186::real, ARRAY[384])::vector, array_fill(0.187::real, ARRAY[384])::vector, array_fill(0.188::real, ARRAY[384])::vector),
    (1192, array_fill(0.189::real, ARRAY[384])::vector, array_fill(0.190::real, ARRAY[384])::vector, array_fill(0.191::real, ARRAY[384])::vector, array_fill(0.192::real, ARRAY[384])::vector),
    (1193, array_fill(0.193::real, ARRAY[384])::vector, array_fill(0.194::real, ARRAY[384])::vector, array_fill(0.195::real, ARRAY[384])::vector, array_fill(0.196::real, ARRAY[384])::vector);
