-- Normal Job/CV seed data for public JobConnect search.
-- This file seeds the normal PostgreSQL tables only: users, jobs, cvs.
-- It does not read or insert V2 scenario JSON or V2 prototype tables.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

INSERT INTO users (id, email, password_hash, full_name, role)
VALUES
    (
        '99999999-9999-9999-9999-999999999991',
        'demo.recruiter@example.com',
        crypt('12345678', gen_salt('bf')),
        'Demo Recruiter',
        'employer'
    ),
    (
        '99999999-9999-9999-9999-999999999992',
        'demo.candidate@example.com',
        crypt('12345678', gen_salt('bf')),
        'Demo Candidate',
        'candidate'
    )
ON CONFLICT (id) DO UPDATE
SET email = EXCLUDED.email,
    full_name = EXCLUDED.full_name,
    role = EXCLUDED.role;

INSERT INTO jobs (
    id,
    created_by,
    title,
    slug,
    status,
    visibility,
    company_name,
    company_location,
    company_size,
    company_industry,
    department,
    location,
    employment_type,
    seniority,
    description,
    responsibilities,
    requirements,
    skills,
    education_level,
    salary,
    benefits,
    tags,
    categories,
    remote,
    archived
)
VALUES
(
    '91000000-0000-0000-0000-000000000001',
    '99999999-9999-9999-9999-999999999991',
    'Senior Backend DevOps Engineer',
    'senior-backend-devops-engineer',
    'published',
    'public',
    'Demo Tech Company',
    'Hanoi',
    '100-500',
    'Information Technology',
    'Engineering',
    '{"city":"Hanoi","country":"Vietnam","remote_type":"remote"}'::jsonb,
    ARRAY['fulltime'],
    'senior',
    'Build and operate Python backend services on Kubernetes with AWS infrastructure.',
    ARRAY['Build backend services', 'Maintain CI/CD', 'Operate cloud infrastructure'],
    ARRAY['Python', 'FastAPI', 'PostgreSQL', 'Docker', 'Kubernetes', 'AWS'],
    '[{"name":"Python","level":"advanced"},{"name":"FastAPI","level":"advanced"},{"name":"PostgreSQL","level":"intermediate"},{"name":"Docker","level":"intermediate"},{"name":"Kubernetes","level":"intermediate"},{"name":"AWS","level":"intermediate"}]'::jsonb,
    'bachelor',
    '{"min":25000000,"max":45000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Remote work', 'Health insurance'],
    ARRAY['python','backend','devops','aws'],
    ARRAY['Software Engineering','DevOps'],
    true,
    false
),
(
    '91000000-0000-0000-0000-000000000002',
    '99999999-9999-9999-9999-999999999991',
    'Frontend Platform Lead',
    'frontend-platform-lead',
    'published',
    'public',
    'Demo Tech Company',
    'Ho Chi Minh City',
    '100-500',
    'Information Technology',
    'Engineering',
    '{"city":"Ho Chi Minh City","country":"Vietnam","remote_type":"hybrid"}'::jsonb,
    ARRAY['fulltime'],
    'lead',
    'Lead a frontend platform team building React, TypeScript, and design system foundations.',
    ARRAY['Lead frontend architecture', 'Coach engineers', 'Improve component quality'],
    ARRAY['React', 'TypeScript', 'Design systems', 'Frontend leadership'],
    '[{"name":"React","level":"advanced"},{"name":"TypeScript","level":"advanced"},{"name":"Design System","level":"intermediate"},{"name":"Leadership","level":"intermediate"}]'::jsonb,
    'bachelor',
    '{"min":35000000,"max":60000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Hybrid work', 'Leadership allowance'],
    ARRAY['react','frontend','typescript','leadership'],
    ARRAY['Software Engineering','Frontend'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000003',
    '99999999-9999-9999-9999-999999999991',
    'Digital Marketing Executive',
    'digital-marketing-executive',
    'published',
    'public',
    'Blue Ocean Media',
    'Ho Chi Minh City',
    '50-100',
    'Marketing',
    'Growth',
    '{"city":"Ho Chi Minh City","country":"Vietnam","remote_type":"onsite"}'::jsonb,
    ARRAY['fulltime'],
    'junior',
    'Plan digital campaigns, manage content calendars, and report marketing performance.',
    ARRAY['Run digital campaigns', 'Coordinate content production', 'Report channel performance'],
    ARRAY['Digital marketing', 'Content planning', 'Excel or reporting skills'],
    '[{"name":"Digital Marketing","level":"intermediate"},{"name":"Content Planning","level":"intermediate"},{"name":"Excel","level":"basic"}]'::jsonb,
    'bachelor',
    '{"min":12000000,"max":20000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Training budget', 'Performance bonus'],
    ARRAY['marketing','content','campaign'],
    ARRAY['Marketing'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000004',
    '99999999-9999-9999-9999-999999999991',
    'Sales Representative',
    'sales-representative',
    'published',
    'public',
    'North Star Trading',
    'Da Nang',
    '100-500',
    'Sales',
    'Commercial',
    '{"city":"Da Nang","country":"Vietnam","remote_type":"onsite"}'::jsonb,
    ARRAY['fulltime'],
    'entry_level',
    'Develop B2B customer relationships and manage sales opportunities.',
    ARRAY['Prospect new customers', 'Prepare proposals', 'Maintain CRM records'],
    ARRAY['Communication skills', 'Customer service mindset', 'Sales motivation'],
    '[{"name":"Sales","level":"basic"},{"name":"Communication","level":"intermediate"},{"name":"Customer Service","level":"basic"}]'::jsonb,
    'college',
    '{"min":10000000,"max":18000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Commission', 'Sales training'],
    ARRAY['sales','b2b','crm'],
    ARRAY['Sales','Customer Service'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000005',
    '99999999-9999-9999-9999-999999999991',
    'Accountant',
    'accountant',
    'published',
    'public',
    'Green Ledger Co.',
    'Hanoi',
    '20-50',
    'Accounting',
    'Finance',
    '{"city":"Hanoi","country":"Vietnam","remote_type":"onsite"}'::jsonb,
    ARRAY['fulltime'],
    'junior',
    'Handle daily accounting records, invoices, and monthly financial reports.',
    ARRAY['Record transactions', 'Reconcile invoices', 'Prepare monthly reports'],
    ARRAY['Accounting knowledge', 'Excel proficiency', 'Attention to detail'],
    '[{"name":"Accounting","level":"intermediate"},{"name":"Excel","level":"intermediate"},{"name":"Financial Reporting","level":"basic"}]'::jsonb,
    'bachelor',
    '{"min":11000000,"max":18000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Annual leave', 'Insurance'],
    ARRAY['accounting','excel','finance'],
    ARRAY['Accounting / Finance'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000006',
    '99999999-9999-9999-9999-999999999991',
    'Financial Analyst',
    'financial-analyst',
    'published',
    'public',
    'Capital Bridge',
    'Ho Chi Minh City',
    '100-500',
    'Finance',
    'Finance',
    '{"city":"Ho Chi Minh City","country":"Vietnam","remote_type":"hybrid"}'::jsonb,
    ARRAY['fulltime'],
    'mid',
    'Analyze business performance and support planning decisions with financial models.',
    ARRAY['Build financial models', 'Analyze monthly performance', 'Prepare management dashboards'],
    ARRAY['Financial analysis', 'Excel', 'Presentation skills'],
    '[{"name":"Financial Analysis","level":"intermediate"},{"name":"Excel","level":"advanced"},{"name":"Presentation","level":"basic"}]'::jsonb,
    'bachelor',
    '{"min":22000000,"max":35000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Hybrid work', 'Performance bonus'],
    ARRAY['finance','analysis','excel'],
    ARRAY['Accounting / Finance'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000007',
    '99999999-9999-9999-9999-999999999991',
    'HR Recruitment Specialist',
    'hr-recruitment-specialist',
    'published',
    'public',
    'PeopleFirst Vietnam',
    'Hanoi',
    '100-500',
    'Human Resources',
    'Human Resources',
    '{"city":"Hanoi","country":"Vietnam","remote_type":"hybrid"}'::jsonb,
    ARRAY['fulltime'],
    'mid',
    'Own end-to-end recruitment for operations and business teams.',
    ARRAY['Source candidates', 'Coordinate interviews', 'Improve hiring funnels'],
    ARRAY['Recruitment experience', 'Interview coordination', 'Communication'],
    '[{"name":"Recruitment","level":"intermediate"},{"name":"Interviewing","level":"intermediate"},{"name":"Communication","level":"intermediate"}]'::jsonb,
    'bachelor',
    '{"min":18000000,"max":30000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Hybrid work', 'Training budget'],
    ARRAY['hr','recruitment','people'],
    ARRAY['Human Resources'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000008',
    '99999999-9999-9999-9999-999999999991',
    'English Teacher',
    'english-teacher',
    'published',
    'public',
    'Bright Future Academy',
    'Can Tho',
    '50-100',
    'Education',
    'Training',
    '{"city":"Can Tho","country":"Vietnam","remote_type":"onsite"}'::jsonb,
    ARRAY['fulltime','parttime'],
    'junior',
    'Teach English communication classes for young learners and adults.',
    ARRAY['Prepare lessons', 'Teach classes', 'Evaluate student progress'],
    ARRAY['English fluency', 'Teaching skills', 'Classroom management'],
    '[{"name":"English","level":"advanced"},{"name":"Teaching","level":"intermediate"},{"name":"Communication","level":"intermediate"}]'::jsonb,
    'bachelor',
    '{"min":12000000,"max":24000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Training materials', 'Flexible schedule'],
    ARRAY['education','english','training'],
    ARRAY['Education / Training'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000009',
    '99999999-9999-9999-9999-999999999991',
    'Healthcare Assistant',
    'healthcare-assistant',
    'published',
    'public',
    'CarePlus Clinic',
    'Binh Duong',
    '100-500',
    'Healthcare',
    'Operations',
    '{"city":"Binh Duong","country":"Vietnam","remote_type":"onsite"}'::jsonb,
    ARRAY['fulltime'],
    'entry_level',
    'Support patients, appointments, and daily clinic operations.',
    ARRAY['Welcome patients', 'Schedule appointments', 'Maintain patient records'],
    ARRAY['Customer service', 'Basic computer skills', 'Careful communication'],
    '[{"name":"Customer Service","level":"intermediate"},{"name":"Communication","level":"intermediate"},{"name":"Administration","level":"basic"}]'::jsonb,
    'high_school',
    '{"min":9000000,"max":14000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Healthcare benefits', 'Shift allowance'],
    ARRAY['healthcare','clinic','customer-service'],
    ARRAY['Healthcare','Customer Service'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000010',
    '99999999-9999-9999-9999-999999999991',
    'UI/UX Designer',
    'ui-ux-designer',
    'published',
    'public',
    'Creative House',
    'Hanoi',
    '20-50',
    'Design',
    'Creative',
    '{"city":"Hanoi","country":"Vietnam","remote_type":"hybrid"}'::jsonb,
    ARRAY['fulltime'],
    'mid',
    'Design user flows, prototypes, and interface systems for web products.',
    ARRAY['Create wireframes', 'Build prototypes', 'Collaborate with product teams'],
    ARRAY['Figma', 'User research', 'Interface design'],
    '[{"name":"Figma","level":"advanced"},{"name":"User Research","level":"intermediate"},{"name":"UI Design","level":"intermediate"}]'::jsonb,
    'bachelor',
    '{"min":18000000,"max":32000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Creative budget', 'Hybrid work'],
    ARRAY['design','figma','ux'],
    ARRAY['Design / Creative'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000011',
    '99999999-9999-9999-9999-999999999991',
    'Logistics Coordinator',
    'logistics-coordinator',
    'published',
    'public',
    'FastLine Logistics',
    'Hai Phong',
    '500-1000',
    'Logistics',
    'Supply Chain',
    '{"city":"Hai Phong","country":"Vietnam","remote_type":"onsite"}'::jsonb,
    ARRAY['fulltime'],
    'junior',
    'Coordinate shipments, delivery schedules, and warehouse communication.',
    ARRAY['Track shipments', 'Coordinate vendors', 'Update delivery records'],
    ARRAY['Logistics knowledge', 'Excel', 'Problem solving'],
    '[{"name":"Logistics","level":"basic"},{"name":"Excel","level":"intermediate"},{"name":"Problem Solving","level":"basic"}]'::jsonb,
    'college',
    '{"min":12000000,"max":20000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Insurance', 'Meal allowance'],
    ARRAY['logistics','supply-chain','excel'],
    ARRAY['Logistics / Supply Chain'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000012',
    '99999999-9999-9999-9999-999999999991',
    'Customer Service Agent',
    'customer-service-agent',
    'published',
    'public',
    'HappyCall Vietnam',
    'Ho Chi Minh City',
    '100-500',
    'Customer Service',
    'Support',
    '{"city":"Ho Chi Minh City","country":"Vietnam","remote_type":"onsite"}'::jsonb,
    ARRAY['fulltime'],
    'entry_level',
    'Assist customers through phone, email, and chat support channels.',
    ARRAY['Respond to inquiries', 'Resolve customer issues', 'Escalate product feedback'],
    ARRAY['Customer service attitude', 'Communication skills', 'Basic computer skills'],
    '[{"name":"Customer Service","level":"intermediate"},{"name":"Communication","level":"intermediate"},{"name":"CRM","level":"basic"}]'::jsonb,
    'high_school',
    '{"min":9000000,"max":15000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Shift allowance', 'Training'],
    ARRAY['customer-service','support','communication'],
    ARRAY['Customer Service'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000013',
    '99999999-9999-9999-9999-999999999991',
    'Manufacturing Supervisor',
    'manufacturing-supervisor',
    'published',
    'public',
    'Precision Factory',
    'Dong Nai',
    '1000+',
    'Manufacturing',
    'Production',
    '{"city":"Dong Nai","country":"Vietnam","remote_type":"onsite"}'::jsonb,
    ARRAY['fulltime'],
    'manager',
    'Supervise production shifts and improve operational quality.',
    ARRAY['Manage production team', 'Track output quality', 'Improve shift efficiency'],
    ARRAY['Manufacturing experience', 'Team leadership', 'Quality mindset'],
    '[{"name":"Manufacturing","level":"intermediate"},{"name":"Leadership","level":"intermediate"},{"name":"Quality Control","level":"basic"}]'::jsonb,
    'college',
    '{"min":25000000,"max":40000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Transport support', 'Management allowance'],
    ARRAY['manufacturing','production','leadership'],
    ARRAY['Manufacturing'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000014',
    '99999999-9999-9999-9999-999999999991',
    'Legal Assistant',
    'legal-assistant',
    'published',
    'public',
    'Trust Law Office',
    'Hanoi',
    '20-50',
    'Legal',
    'Legal',
    '{"city":"Hanoi","country":"Vietnam","remote_type":"onsite"}'::jsonb,
    ARRAY['fulltime'],
    'junior',
    'Support legal consultants with documentation, research, and client files.',
    ARRAY['Prepare documents', 'Research legal information', 'Manage client records'],
    ARRAY['Legal knowledge', 'Document management', 'Attention to detail'],
    '[{"name":"Legal Research","level":"basic"},{"name":"Document Management","level":"intermediate"},{"name":"Attention to Detail","level":"intermediate"}]'::jsonb,
    'bachelor',
    '{"min":10000000,"max":18000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Professional training', 'Insurance'],
    ARRAY['legal','documents','research'],
    ARRAY['Legal'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000015',
    '99999999-9999-9999-9999-999999999991',
    'Real Estate Consultant',
    'real-estate-consultant',
    'published',
    'public',
    'UrbanHome Realty',
    'Ho Chi Minh City',
    '100-500',
    'Real Estate',
    'Sales',
    '{"city":"Ho Chi Minh City","country":"Vietnam","remote_type":"onsite"}'::jsonb,
    ARRAY['fulltime'],
    'entry_level',
    'Consult customers on residential property options and manage sales pipeline.',
    ARRAY['Advise customers', 'Arrange property visits', 'Update sales pipeline'],
    ARRAY['Sales mindset', 'Communication', 'Customer relationship skills'],
    '[{"name":"Sales","level":"basic"},{"name":"Communication","level":"intermediate"},{"name":"Customer Relationship","level":"basic"}]'::jsonb,
    'college',
    '{"min":8000000,"max":25000000,"currency":"VND","period":"month","note":"base plus commission"}'::jsonb,
    ARRAY['Commission', 'Sales leads'],
    ARRAY['real-estate','sales','consulting'],
    ARRAY['Real Estate','Sales'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000016',
    '99999999-9999-9999-9999-999999999991',
    'Hotel Receptionist',
    'hotel-receptionist',
    'published',
    'public',
    'Sunrise Hotel Group',
    'Da Nang',
    '100-500',
    'Hospitality',
    'Front Office',
    '{"city":"Da Nang","country":"Vietnam","remote_type":"onsite"}'::jsonb,
    ARRAY['fulltime'],
    'entry_level',
    'Welcome guests, handle reservations, and support front office operations.',
    ARRAY['Check in guests', 'Handle reservations', 'Coordinate guest requests'],
    ARRAY['Hospitality service', 'English communication', 'Shift availability'],
    '[{"name":"Hospitality","level":"basic"},{"name":"English","level":"intermediate"},{"name":"Customer Service","level":"intermediate"}]'::jsonb,
    'high_school',
    '{"min":9000000,"max":15000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Service charge', 'Meal allowance'],
    ARRAY['hospitality','hotel','front-office'],
    ARRAY['Hospitality / Tourism','Customer Service'],
    false,
    false
)
ON CONFLICT (id) DO UPDATE
SET created_by = EXCLUDED.created_by,
    title = EXCLUDED.title,
    slug = EXCLUDED.slug,
    status = 'published',
    visibility = 'public',
    company_name = EXCLUDED.company_name,
    company_location = EXCLUDED.company_location,
    company_size = EXCLUDED.company_size,
    company_industry = EXCLUDED.company_industry,
    department = EXCLUDED.department,
    location = EXCLUDED.location,
    employment_type = EXCLUDED.employment_type,
    seniority = EXCLUDED.seniority,
    description = EXCLUDED.description,
    responsibilities = EXCLUDED.responsibilities,
    requirements = EXCLUDED.requirements,
    skills = EXCLUDED.skills,
    education_level = EXCLUDED.education_level,
    salary = EXCLUDED.salary,
    benefits = EXCLUDED.benefits,
    tags = EXCLUDED.tags,
    categories = EXCLUDED.categories,
    remote = EXCLUDED.remote,
    archived = false;

INSERT INTO cvs (
    id,
    created_by,
    fullname,
    email,
    phone,
    location,
    headline,
    summary,
    target_role,
    employment_type,
    availability,
    skills,
    experiences,
    education,
    projects,
    certifications,
    languages,
    tags,
    status,
    visibility,
    file,
    archived
)
VALUES
(
    '92000000-0000-0000-0000-000000000001',
    '99999999-9999-9999-9999-999999999992',
    'Nguyen Van A',
    'candidate.frontend@example.com',
    '0900000001',
    '{"city":"Ho Chi Minh City","country":"Vietnam","remote_type":"hybrid"}'::jsonb,
    'Junior Frontend Developer',
    'Frontend developer with React, TypeScript, and Tailwind experience.',
    'Frontend Developer',
    ARRAY['fulltime'],
    'within_1_month',
    '[{"name":"React","level":"intermediate","category":"Frontend","years":1},{"name":"TypeScript","level":"basic","category":"Frontend","years":1},{"name":"Tailwind CSS","level":"basic","category":"Frontend","years":1}]'::jsonb,
    '[{"title":"Frontend Intern","company":"Demo Software Company","responsibilities":["Built React components","Integrated REST APIs"],"achievements":["Improved UI performance"]}]'::jsonb,
    '[{"degree":"Bachelor","major":"Information Technology","school":"Demo University"}]'::jsonb,
    '[{"name":"Dashboard UI","description":"Built reusable dashboard components","techStack":["React","TypeScript"]}]'::jsonb,
    '[]'::jsonb,
    '[{"name":"English","level":"intermediate"}]'::jsonb,
    ARRAY['react','frontend','typescript'],
    'published',
    'public',
    '{}'::jsonb,
    false
),
(
    '92000000-0000-0000-0000-000000000002',
    '99999999-9999-9999-9999-999999999992',
    'Tran Thi B',
    'candidate.marketing@example.com',
    '0900000002',
    '{"city":"Ho Chi Minh City","country":"Vietnam","remote_type":"onsite"}'::jsonb,
    'Digital Marketing Specialist',
    'Marketing candidate with campaign planning, content, and reporting experience.',
    'Digital Marketing Executive',
    ARRAY['fulltime'],
    'immediately',
    '[{"name":"Digital Marketing","level":"intermediate","category":"Marketing","years":2},{"name":"Content Planning","level":"intermediate","category":"Marketing","years":2},{"name":"Excel","level":"basic","category":"Office","years":2}]'::jsonb,
    '[{"title":"Marketing Executive","company":"Retail Brand","responsibilities":["Planned campaigns","Reported channel performance"],"achievements":["Increased lead volume"]}]'::jsonb,
    '[{"degree":"Bachelor","major":"Marketing","school":"Demo Economics University"}]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[{"name":"English","level":"intermediate"}]'::jsonb,
    ARRAY['marketing','content','campaign'],
    'published',
    'public',
    '{}'::jsonb,
    false
),
(
    '92000000-0000-0000-0000-000000000003',
    '99999999-9999-9999-9999-999999999992',
    'Le Minh C',
    'candidate.accounting@example.com',
    '0900000003',
    '{"city":"Hanoi","country":"Vietnam","remote_type":"onsite"}'::jsonb,
    'Accountant',
    'Accounting candidate experienced with invoices, reconciliation, and Excel reports.',
    'Accountant',
    ARRAY['fulltime'],
    'within_1_week',
    '[{"name":"Accounting","level":"intermediate","category":"Finance","years":3},{"name":"Excel","level":"advanced","category":"Office","years":4},{"name":"Financial Reporting","level":"basic","category":"Finance","years":2}]'::jsonb,
    '[{"title":"Accounting Assistant","company":"Trading Company","responsibilities":["Recorded transactions","Reconciled invoices"],"achievements":["Reduced reporting errors"]}]'::jsonb,
    '[{"degree":"Bachelor","major":"Accounting","school":"Demo Finance University"}]'::jsonb,
    '[]'::jsonb,
    '[{"name":"Chief Accountant Training","issuer":"Demo Institute"}]'::jsonb,
    '[{"name":"English","level":"basic"}]'::jsonb,
    ARRAY['accounting','excel','finance'],
    'published',
    'public',
    '{}'::jsonb,
    false
),
(
    '92000000-0000-0000-0000-000000000004',
    '99999999-9999-9999-9999-999999999992',
    'Pham Quoc D',
    'candidate.logistics@example.com',
    '0900000004',
    '{"city":"Hai Phong","country":"Vietnam","remote_type":"onsite"}'::jsonb,
    'Logistics Coordinator',
    'Logistics candidate with shipment tracking, vendor coordination, and warehouse communication experience.',
    'Logistics Coordinator',
    ARRAY['fulltime'],
    'immediately',
    '[{"name":"Logistics","level":"intermediate","category":"Supply Chain","years":2},{"name":"Excel","level":"intermediate","category":"Office","years":3},{"name":"Problem Solving","level":"basic","category":"Soft Skill","years":2}]'::jsonb,
    '[{"title":"Logistics Staff","company":"Warehouse Operator","responsibilities":["Tracked shipments","Updated delivery records"],"achievements":["Improved dispatch accuracy"]}]'::jsonb,
    '[{"degree":"College","major":"Logistics","school":"Demo College"}]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[{"name":"English","level":"basic"}]'::jsonb,
    ARRAY['logistics','supply-chain','excel'],
    'published',
    'public',
    '{}'::jsonb,
    false
),
(
    '92000000-0000-0000-0000-000000000005',
    '99999999-9999-9999-9999-999999999992',
    'Hoang Thi E',
    'candidate.design@example.com',
    '0900000005',
    '{"city":"Hanoi","country":"Vietnam","remote_type":"hybrid"}'::jsonb,
    'UI/UX Designer',
    'Designer with Figma, user flow, and interface design experience.',
    'UI/UX Designer',
    ARRAY['fulltime'],
    'negotiable',
    '[{"name":"Figma","level":"advanced","category":"Design","years":3},{"name":"User Research","level":"intermediate","category":"Design","years":2},{"name":"UI Design","level":"intermediate","category":"Design","years":3}]'::jsonb,
    '[{"title":"Product Designer","company":"Creative Studio","responsibilities":["Created prototypes","Ran usability reviews"],"achievements":["Improved task completion rate"]}]'::jsonb,
    '[{"degree":"Bachelor","major":"Graphic Design","school":"Demo Art University"}]'::jsonb,
    '[{"name":"Mobile App Redesign","description":"Redesigned onboarding flow","techStack":["Figma"]}]'::jsonb,
    '[]'::jsonb,
    '[{"name":"English","level":"intermediate"}]'::jsonb,
    ARRAY['design','figma','ux'],
    'published',
    'public',
    '{}'::jsonb,
    false
),
(
    '92000000-0000-0000-0000-000000000006',
    '99999999-9999-9999-9999-999999999992',
    'Do Van F',
    'candidate.sales@example.com',
    '0900000006',
    '{"city":"Da Nang","country":"Vietnam","remote_type":"onsite"}'::jsonb,
    'Sales Representative',
    'Sales candidate with B2B prospecting and customer relationship experience.',
    'Sales Representative',
    ARRAY['fulltime'],
    'immediately',
    '[{"name":"Sales","level":"intermediate","category":"Sales","years":2},{"name":"Communication","level":"intermediate","category":"Soft Skill","years":3},{"name":"CRM","level":"basic","category":"Tool","years":1}]'::jsonb,
    '[{"title":"Sales Staff","company":"Distribution Company","responsibilities":["Prospected customers","Prepared quotations"],"achievements":["Exceeded monthly target"]}]'::jsonb,
    '[{"degree":"College","major":"Business Administration","school":"Demo College"}]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[{"name":"English","level":"basic"}]'::jsonb,
    ARRAY['sales','b2b','crm'],
    'published',
    'public',
    '{}'::jsonb,
    false
),
(
    '92000000-0000-0000-0000-000000000007',
    '99999999-9999-9999-9999-999999999992',
    'Vu Thi G',
    'candidate.hr@example.com',
    '0900000007',
    '{"city":"Hanoi","country":"Vietnam","remote_type":"hybrid"}'::jsonb,
    'HR Recruitment Specialist',
    'Recruiter with sourcing, screening, and interview coordination experience.',
    'HR Recruitment Specialist',
    ARRAY['fulltime'],
    'within_1_month',
    '[{"name":"Recruitment","level":"intermediate","category":"Human Resources","years":3},{"name":"Interviewing","level":"intermediate","category":"Human Resources","years":2},{"name":"Communication","level":"intermediate","category":"Soft Skill","years":3}]'::jsonb,
    '[{"title":"Recruitment Executive","company":"People Services","responsibilities":["Sourced candidates","Coordinated interviews"],"achievements":["Reduced hiring lead time"]}]'::jsonb,
    '[{"degree":"Bachelor","major":"Human Resources","school":"Demo University"}]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[{"name":"English","level":"intermediate"}]'::jsonb,
    ARRAY['hr','recruitment','people'],
    'published',
    'public',
    '{}'::jsonb,
    false
),
(
    '92000000-0000-0000-0000-000000000008',
    '99999999-9999-9999-9999-999999999992',
    'Bui Minh H',
    'candidate.hospitality@example.com',
    '0900000008',
    '{"city":"Da Nang","country":"Vietnam","remote_type":"onsite"}'::jsonb,
    'Hotel Receptionist',
    'Hospitality candidate experienced with guest service, reservations, and English communication.',
    'Hotel Receptionist',
    ARRAY['fulltime'],
    'immediately',
    '[{"name":"Hospitality","level":"intermediate","category":"Hospitality","years":2},{"name":"English","level":"intermediate","category":"Language","years":3},{"name":"Customer Service","level":"intermediate","category":"Service","years":3}]'::jsonb,
    '[{"title":"Front Desk Staff","company":"Beach Hotel","responsibilities":["Checked in guests","Handled reservations"],"achievements":["Improved guest satisfaction"]}]'::jsonb,
    '[{"degree":"High School","major":"General","school":"Demo High School"}]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[{"name":"English","level":"intermediate"}]'::jsonb,
    ARRAY['hospitality','hotel','front-office'],
    'published',
    'public',
    '{}'::jsonb,
    false
)
ON CONFLICT (id) DO UPDATE
SET created_by = EXCLUDED.created_by,
    fullname = EXCLUDED.fullname,
    email = EXCLUDED.email,
    phone = EXCLUDED.phone,
    location = EXCLUDED.location,
    headline = EXCLUDED.headline,
    summary = EXCLUDED.summary,
    target_role = EXCLUDED.target_role,
    employment_type = EXCLUDED.employment_type,
    availability = EXCLUDED.availability,
    skills = EXCLUDED.skills,
    experiences = EXCLUDED.experiences,
    education = EXCLUDED.education,
    projects = EXCLUDED.projects,
    certifications = EXCLUDED.certifications,
    languages = EXCLUDED.languages,
    tags = EXCLUDED.tags,
    status = 'published',
    visibility = 'public',
    file = EXCLUDED.file,
    archived = false;

UPDATE jobs
SET industry = CASE
        WHEN company_industry ILIKE '%Information Technology%' OR company_industry ILIKE '%Software%' THEN 'information_technology'
        WHEN company_industry ILIKE '%Accounting%' OR company_industry ILIKE '%Finance%' THEN 'accounting_finance'
        WHEN company_industry ILIKE '%Sales%' THEN 'sales'
        WHEN company_industry ILIKE '%Marketing%' THEN 'marketing'
        WHEN company_industry ILIKE '%Human Resources%' OR company_industry ILIKE '%HR%' THEN 'human_resources'
        WHEN company_industry ILIKE '%Education%' THEN 'education'
        WHEN company_industry ILIKE '%Healthcare%' THEN 'healthcare'
        WHEN company_industry ILIKE '%Construction%' OR company_industry ILIKE '%Engineering%' THEN 'engineering_construction'
        WHEN company_industry ILIKE '%Design%' OR company_industry ILIKE '%Creative%' THEN 'design_creative'
        WHEN company_industry ILIKE '%Customer Service%' THEN 'customer_service'
        WHEN company_industry ILIKE '%Operations%' THEN 'operations'
        WHEN company_industry ILIKE '%Logistics%' OR company_industry ILIKE '%Supply Chain%' THEN 'logistics_supply_chain'
        WHEN company_industry ILIKE '%Hospitality%' OR company_industry ILIKE '%Tourism%' THEN 'hospitality_tourism'
        WHEN company_industry ILIKE '%Legal%' THEN 'legal'
        WHEN company_industry ILIKE '%Manufacturing%' THEN 'manufacturing'
        WHEN company_industry ILIKE '%Retail%' THEN 'retail'
        ELSE 'unknown'
    END,
    occupation_group = CASE
        WHEN title ILIKE '%DevOps%' THEN 'devops_cloud'
        WHEN title ILIKE '%Backend%' OR title ILIKE '%Frontend%' OR title ILIKE '%Developer%' OR title ILIKE '%Engineer%' THEN 'software_engineering'
        WHEN title ILIKE '%Marketing%' THEN 'digital_marketing'
        WHEN title ILIKE '%Sales%' THEN 'sales_executive'
        WHEN title ILIKE '%Accountant%' OR title ILIKE '%Accounting%' THEN 'accountant'
        WHEN title ILIKE '%Finance%' THEN 'financial_analyst'
        WHEN title ILIKE '%HR%' OR title ILIKE '%Recruit%' THEN 'hr_recruitment'
        WHEN title ILIKE '%Teacher%' THEN 'teacher'
        WHEN title ILIKE '%Doctor%' THEN 'doctor'
        WHEN title ILIKE '%Nurse%' THEN 'nurse'
        WHEN title ILIKE '%Designer%' THEN 'ui_ux_designer'
        WHEN title ILIKE '%Customer%' THEN 'customer_support'
        WHEN title ILIKE '%Logistics%' THEN 'logistics_staff'
        WHEN title ILIKE '%Legal%' THEN 'legal_staff'
        WHEN title ILIKE '%Production%' THEN 'production_worker'
        WHEN title ILIKE '%Retail%' THEN 'retail_staff'
        WHEN title ILIKE '%Hotel%' THEN 'hotel_staff'
        ELSE 'unknown'
    END
WHERE id::text LIKE '91000000-0000-0000-0000-%';

UPDATE cvs
SET industry = CASE
        WHEN target_role ILIKE '%Developer%' OR target_role ILIKE '%Backend%' OR target_role ILIKE '%Frontend%' OR summary ILIKE '%React%' OR summary ILIKE '%Python%' THEN 'information_technology'
        WHEN target_role ILIKE '%Account%' OR summary ILIKE '%Finance%' THEN 'accounting_finance'
        WHEN target_role ILIKE '%Sales%' THEN 'sales'
        WHEN target_role ILIKE '%Marketing%' THEN 'marketing'
        WHEN target_role ILIKE '%HR%' OR target_role ILIKE '%Recruit%' THEN 'human_resources'
        WHEN target_role ILIKE '%Teacher%' THEN 'education'
        WHEN target_role ILIKE '%Doctor%' OR target_role ILIKE '%Nurse%' THEN 'healthcare'
        WHEN target_role ILIKE '%Designer%' OR summary ILIKE '%Figma%' THEN 'design_creative'
        WHEN target_role ILIKE '%Logistics%' THEN 'logistics_supply_chain'
        WHEN target_role ILIKE '%Customer%' THEN 'customer_service'
        WHEN target_role ILIKE '%Hotel%' OR target_role ILIKE '%Receptionist%' THEN 'hospitality_tourism'
        ELSE 'unknown'
    END,
    occupation_group = CASE
        WHEN target_role ILIKE '%Backend%' OR target_role ILIKE '%Frontend%' OR target_role ILIKE '%Developer%' THEN 'software_engineering'
        WHEN target_role ILIKE '%Account%' THEN 'accountant'
        WHEN target_role ILIKE '%Sales%' THEN 'sales_executive'
        WHEN target_role ILIKE '%Marketing%' THEN 'digital_marketing'
        WHEN target_role ILIKE '%HR%' OR target_role ILIKE '%Recruit%' THEN 'hr_recruitment'
        WHEN target_role ILIKE '%Teacher%' THEN 'teacher'
        WHEN target_role ILIKE '%Designer%' THEN 'ui_ux_designer'
        WHEN target_role ILIKE '%Customer%' THEN 'customer_support'
        WHEN target_role ILIKE '%Hotel%' OR target_role ILIKE '%Receptionist%' THEN 'hotel_staff'
        ELSE 'unknown'
    END
WHERE id::text LIKE '92000000-0000-0000-0000-%';
