-- Vietnamese normal Job/CV seed data for public JobConnect search.
-- This file seeds the normal PostgreSQL tables only: users, jobs, cvs.
-- It does not read or insert V2 scenario JSON or V2 prototype tables.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

INSERT INTO users (id, email, password_hash, full_name, role)
VALUES
    (
        '99999999-9999-9999-9999-999999999991',
        'demo.recruiter@example.com',
        crypt('12345678', gen_salt('bf')),
        'Nhà tuyển dụng Demo',
        'employer'
    ),
    (
        '99999999-9999-9999-9999-999999999992',
        'demo.candidate@example.com',
        crypt('12345678', gen_salt('bf')),
        'Ứng viên Demo',
        'candidate'
    )
ON CONFLICT (id) DO UPDATE
SET email = EXCLUDED.email,
    full_name = EXCLUDED.full_name,
    role = EXCLUDED.role;

INSERT INTO jobs (
    id,
    created_by,
    title,
    slug,
    status,
    visibility,
    company_name,
    company_location,
    company_size,
    company_industry,
    industry,
    occupation_group,
    department,
    location,
    employment_type,
    seniority,
    description,
    responsibilities,
    requirements,
    skills,
    tools_and_technologies,
    domain_knowledge,
    experience_years,
    education_level,
    required_education,
    required_certifications,
    salary,
    benefits,
    tags,
    categories,
    remote,
    archived
)
VALUES
(
    '91000000-0000-0000-0000-000000000001',
    '99999999-9999-9999-9999-999999999991',
    'Lập trình viên Backend Python',
    'lap-trinh-vien-backend-python',
    'published',
    'public',
    'Công ty Công nghệ ABC',
    'Hà Nội',
    '100-500',
    'Công nghệ thông tin',
    'information_technology',
    'software_engineering',
    'Kỹ thuật',
    '{"city":"Hà Nội","country":"Việt Nam","remote_type":"hybrid"}'::jsonb,
    ARRAY['fulltime'],
    'middle',
    'Tham gia phát triển hệ thống tuyển dụng và quản lý hồ sơ ứng viên bằng Python, FastAPI và PostgreSQL.',
    ARRAY['Thiết kế REST API', 'Tối ưu truy vấn PostgreSQL', 'Phối hợp triển khai dịch vụ backend'],
    ARRAY['Có kinh nghiệm với Python và FastAPI', 'Biết thiết kế REST API', 'Có kinh nghiệm làm việc với PostgreSQL'],
    '[{"name":"Python","normalized_name":"python","level":"advanced","category":"technical"},{"name":"FastAPI","normalized_name":"fastapi","level":"intermediate","category":"technical"},{"name":"PostgreSQL","normalized_name":"postgresql","level":"intermediate","category":"technical"}]'::jsonb,
    ARRAY['FastAPI','PostgreSQL','Docker'],
    ARRAY['ecommerce','recruitment'],
    3,
    'bachelor',
    '{"level":"bachelor","major":"Công nghệ thông tin"}'::jsonb,
    ARRAY[]::text[],
    '{"min":25000000,"max":45000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Bảo hiểm sức khỏe', 'Làm việc hybrid'],
    ARRAY['python','backend','fastapi'],
    ARRAY['Công nghệ thông tin'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000002',
    '99999999-9999-9999-9999-999999999991',
    'Trưởng nhóm Frontend React',
    'truong-nhom-frontend-react',
    'published',
    'public',
    'Công ty Nền tảng Số',
    'TP. Hồ Chí Minh',
    '100-500',
    'Công nghệ thông tin',
    'information_technology',
    'software_engineering',
    'Kỹ thuật',
    '{"city":"TP. Hồ Chí Minh","country":"Việt Nam","remote_type":"hybrid"}'::jsonb,
    ARRAY['fulltime'],
    'lead',
    'Dẫn dắt nhóm frontend xây dựng giao diện React, TypeScript và hệ thống thiết kế dùng chung.',
    ARRAY['Định hướng kiến trúc frontend', 'Huấn luyện lập trình viên', 'Cải thiện chất lượng component'],
    ARRAY['Thành thạo React và TypeScript', 'Có kinh nghiệm xây dựng design system', 'Có kỹ năng dẫn dắt nhóm'],
    '[{"name":"React","normalized_name":"react","level":"advanced","category":"technical"},{"name":"TypeScript","normalized_name":"typescript","level":"advanced","category":"technical"},{"name":"Design System","normalized_name":"design_system","level":"intermediate","category":"technical"}]'::jsonb,
    ARRAY['React','TypeScript','Figma'],
    ARRAY['software_product'],
    5,
    'bachelor',
    '{"level":"bachelor","major":"Công nghệ thông tin"}'::jsonb,
    ARRAY[]::text[],
    '{"min":35000000,"max":60000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Phụ cấp trách nhiệm', 'Làm việc hybrid'],
    ARRAY['react','frontend','typescript'],
    ARRAY['Công nghệ thông tin'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000003',
    '99999999-9999-9999-9999-999999999991',
    'Chuyên viên Digital Marketing',
    'chuyen-vien-digital-marketing',
    'published',
    'public',
    'Công ty Truyền thông Biển Xanh',
    'TP. Hồ Chí Minh',
    '50-100',
    'Marketing',
    'marketing',
    'digital_marketing',
    'Tăng trưởng',
    '{"city":"TP. Hồ Chí Minh","country":"Việt Nam","remote_type":"onsite"}'::jsonb,
    ARRAY['fulltime'],
    'junior',
    'Lập kế hoạch chiến dịch số, quản lý lịch nội dung và báo cáo hiệu quả kênh marketing.',
    ARRAY['Triển khai chiến dịch quảng cáo', 'Phối hợp sản xuất nội dung', 'Theo dõi hiệu quả kênh'],
    ARRAY['Hiểu digital marketing', 'Biết lập kế hoạch nội dung', 'Sử dụng Excel để báo cáo'],
    '[{"name":"Digital Marketing","normalized_name":"digital_marketing","level":"intermediate","category":"marketing"},{"name":"Content Planning","normalized_name":"content_planning","level":"intermediate","category":"marketing"},{"name":"Excel","normalized_name":"excel","level":"basic","category":"tool"}]'::jsonb,
    ARRAY['Meta Ads','Google Analytics','Excel'],
    ARRAY['ecommerce'],
    1,
    'bachelor',
    '{"level":"bachelor","major":"Marketing"}'::jsonb,
    ARRAY[]::text[],
    '{"min":12000000,"max":20000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Ngân sách học tập', 'Thưởng hiệu quả'],
    ARRAY['marketing','content','campaign'],
    ARRAY['Marketing'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000004',
    '99999999-9999-9999-9999-999999999991',
    'Nhân viên Kinh doanh B2B',
    'nhan-vien-kinh-doanh-b2b',
    'published',
    'public',
    'Công ty Thương mại Sao Bắc',
    'Đà Nẵng',
    '100-500',
    'Kinh doanh',
    'sales',
    'sales_executive',
    'Thương mại',
    '{"city":"Đà Nẵng","country":"Việt Nam","remote_type":"onsite"}'::jsonb,
    ARRAY['fulltime'],
    'junior',
    'Phát triển khách hàng doanh nghiệp, tư vấn giải pháp và quản lý cơ hội bán hàng.',
    ARRAY['Tìm kiếm khách hàng mới', 'Chuẩn bị báo giá', 'Cập nhật dữ liệu CRM'],
    ARRAY['Giao tiếp tốt', 'Có tư duy chăm sóc khách hàng', 'Yêu thích công việc kinh doanh'],
    '[{"name":"Sales","normalized_name":"sales","level":"basic","category":"sales"},{"name":"Communication","normalized_name":"communication","level":"intermediate","category":"soft_skill"},{"name":"CRM","normalized_name":"crm","level":"basic","category":"tool"}]'::jsonb,
    ARRAY['CRM','Excel'],
    ARRAY['b2b_sales'],
    1,
    'associate',
    '{"level":"associate","major":"Quản trị kinh doanh"}'::jsonb,
    ARRAY[]::text[],
    '{"min":10000000,"max":18000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Hoa hồng bán hàng', 'Đào tạo sản phẩm'],
    ARRAY['sales','b2b','crm'],
    ARRAY['Kinh doanh'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000005',
    '99999999-9999-9999-9999-999999999991',
    'Kế toán tổng hợp',
    'ke-toan-tong-hop',
    'published',
    'public',
    'Công ty Sổ Sách Xanh',
    'Hà Nội',
    '20-50',
    'Kế toán - Tài chính',
    'accounting_finance',
    'accountant',
    'Tài chính',
    '{"city":"Hà Nội","country":"Việt Nam","remote_type":"onsite"}'::jsonb,
    ARRAY['fulltime'],
    'middle',
    'Phụ trách hạch toán nghiệp vụ, đối chiếu công nợ và lập báo cáo tài chính tháng.',
    ARRAY['Ghi nhận chứng từ kế toán', 'Đối chiếu hóa đơn và công nợ', 'Lập báo cáo tháng'],
    ARRAY['Nắm vững nghiệp vụ kế toán', 'Thành thạo Excel', 'Cẩn thận và có trách nhiệm'],
    '[{"name":"Kế toán","normalized_name":"accounting","level":"intermediate","category":"finance"},{"name":"Excel","normalized_name":"excel","level":"advanced","category":"tool"},{"name":"Báo cáo tài chính","normalized_name":"financial_reporting","level":"intermediate","category":"finance"}]'::jsonb,
    ARRAY['Excel','MISA'],
    ARRAY['accounting','tax'],
    3,
    'bachelor',
    '{"level":"bachelor","major":"Kế toán"}'::jsonb,
    ARRAY['Chứng chỉ kế toán trưởng'],
    '{"min":15000000,"max":25000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Bảo hiểm đầy đủ', 'Thưởng cuối năm'],
    ARRAY['accounting','excel','finance'],
    ARRAY['Kế toán - Tài chính'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000006',
    '99999999-9999-9999-9999-999999999991',
    'Chuyên viên Phân tích Tài chính',
    'chuyen-vien-phan-tich-tai-chinh',
    'published',
    'public',
    'Công ty Cầu Vốn',
    'TP. Hồ Chí Minh',
    '100-500',
    'Tài chính',
    'accounting_finance',
    'financial_analyst',
    'Tài chính',
    '{"city":"TP. Hồ Chí Minh","country":"Việt Nam","remote_type":"hybrid"}'::jsonb,
    ARRAY['fulltime'],
    'middle',
    'Phân tích hiệu quả kinh doanh, xây dựng mô hình tài chính và hỗ trợ lập kế hoạch ngân sách.',
    ARRAY['Xây dựng mô hình tài chính', 'Phân tích hiệu quả tháng', 'Chuẩn bị dashboard quản trị'],
    ARRAY['Có kinh nghiệm phân tích tài chính', 'Thành thạo Excel', 'Trình bày dữ liệu rõ ràng'],
    '[{"name":"Financial Analysis","normalized_name":"financial_analysis","level":"intermediate","category":"finance"},{"name":"Excel","normalized_name":"excel","level":"advanced","category":"tool"},{"name":"Presentation","normalized_name":"presentation","level":"basic","category":"soft_skill"}]'::jsonb,
    ARRAY['Excel','Power BI'],
    ARRAY['finance'],
    3,
    'bachelor',
    '{"level":"bachelor","major":"Tài chính"}'::jsonb,
    ARRAY[]::text[],
    '{"min":22000000,"max":35000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Làm việc hybrid', 'Thưởng hiệu quả'],
    ARRAY['finance','analysis','excel'],
    ARRAY['Kế toán - Tài chính'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000007',
    '99999999-9999-9999-9999-999999999991',
    'Chuyên viên Tuyển dụng',
    'chuyen-vien-tuyen-dung',
    'published',
    'public',
    'Công ty Nhân sự Tiên Phong',
    'Hà Nội',
    '50-100',
    'Nhân sự',
    'human_resources',
    'hr_recruitment',
    'Nhân sự',
    '{"city":"Hà Nội","country":"Việt Nam","remote_type":"hybrid"}'::jsonb,
    ARRAY['fulltime'],
    'middle',
    'Phụ trách tìm kiếm ứng viên, sàng lọc hồ sơ và điều phối phỏng vấn cho các vị trí văn phòng.',
    ARRAY['Tìm kiếm ứng viên', 'Sàng lọc hồ sơ', 'Điều phối lịch phỏng vấn'],
    ARRAY['Có kinh nghiệm tuyển dụng', 'Giao tiếp tốt', 'Biết sử dụng kênh tuyển dụng trực tuyến'],
    '[{"name":"Recruitment","normalized_name":"recruitment","level":"intermediate","category":"human_resources"},{"name":"Interviewing","normalized_name":"interviewing","level":"intermediate","category":"human_resources"},{"name":"Communication","normalized_name":"communication","level":"intermediate","category":"soft_skill"}]'::jsonb,
    ARRAY['LinkedIn','Google Sheets'],
    ARRAY['recruitment'],
    2,
    'bachelor',
    '{"level":"bachelor","major":"Quản trị nhân lực"}'::jsonb,
    ARRAY[]::text[],
    '{"min":18000000,"max":30000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Làm việc hybrid', 'Đào tạo nghiệp vụ'],
    ARRAY['hr','recruitment','people'],
    ARRAY['Nhân sự'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000008',
    '99999999-9999-9999-9999-999999999991',
    'Giáo viên Tiếng Anh',
    'giao-vien-tieng-anh',
    'published',
    'public',
    'Trung tâm Anh ngữ Mekong',
    'Cần Thơ',
    '20-50',
    'Giáo dục',
    'education',
    'teacher',
    'Đào tạo',
    '{"city":"Cần Thơ","country":"Việt Nam","remote_type":"onsite"}'::jsonb,
    ARRAY['fulltime'],
    'middle',
    'Giảng dạy tiếng Anh giao tiếp, thiết kế hoạt động lớp học và theo dõi tiến bộ học viên.',
    ARRAY['Soạn giáo án', 'Giảng dạy lớp giao tiếp', 'Đánh giá tiến bộ học viên'],
    ARRAY['Phát âm tốt', 'Có kinh nghiệm giảng dạy', 'Kiên nhẫn với học viên'],
    '[{"name":"English","normalized_name":"english","level":"advanced","category":"language"},{"name":"Teaching","normalized_name":"teaching","level":"intermediate","category":"education"},{"name":"Communication","normalized_name":"communication","level":"intermediate","category":"soft_skill"}]'::jsonb,
    ARRAY['Google Classroom','Zoom'],
    ARRAY['education'],
    2,
    'bachelor',
    '{"level":"bachelor","major":"Ngôn ngữ Anh"}'::jsonb,
    ARRAY['TESOL'],
    '{"min":12000000,"max":24000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Đào tạo nội bộ', 'Thưởng lớp học'],
    ARRAY['teaching','english','education'],
    ARRAY['Giáo dục'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000009',
    '99999999-9999-9999-9999-999999999991',
    'Điều dưỡng phòng khám',
    'dieu-duong-phong-kham',
    'published',
    'public',
    'Phòng khám An Tâm',
    'Bình Dương',
    '50-100',
    'Y tế',
    'healthcare',
    'nurse',
    'Điều dưỡng',
    '{"city":"Bình Dương","country":"Việt Nam","remote_type":"onsite"}'::jsonb,
    ARRAY['fulltime'],
    'junior',
    'Hỗ trợ bác sĩ trong quy trình khám bệnh, hướng dẫn bệnh nhân và quản lý hồ sơ y tế.',
    ARRAY['Tiếp nhận bệnh nhân', 'Chuẩn bị dụng cụ y tế', 'Cập nhật hồ sơ khám'],
    ARRAY['Có chứng chỉ điều dưỡng', 'Cẩn thận trong quy trình y tế', 'Giao tiếp nhẹ nhàng'],
    '[{"name":"Điều dưỡng","normalized_name":"nursing","level":"intermediate","category":"healthcare"},{"name":"Chăm sóc bệnh nhân","normalized_name":"patient_care","level":"intermediate","category":"healthcare"},{"name":"Hồ sơ y tế","normalized_name":"medical_records","level":"basic","category":"healthcare"}]'::jsonb,
    ARRAY['HIS','Excel'],
    ARRAY['healthcare'],
    1,
    'vocational',
    '{"level":"vocational","major":"Điều dưỡng"}'::jsonb,
    ARRAY['Chứng chỉ hành nghề điều dưỡng'],
    '{"min":9000000,"max":14000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Phụ cấp ca trực', 'Bảo hiểm'],
    ARRAY['healthcare','nurse','clinic'],
    ARRAY['Y tế'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000010',
    '99999999-9999-9999-9999-999999999991',
    'Nhà thiết kế UI/UX',
    'nha-thiet-ke-ui-ux',
    'published',
    'public',
    'Studio Sáng Tạo Việt',
    'Hà Nội',
    '20-50',
    'Thiết kế sáng tạo',
    'design_creative',
    'ui_ux_designer',
    'Sản phẩm',
    '{"city":"Hà Nội","country":"Việt Nam","remote_type":"hybrid"}'::jsonb,
    ARRAY['fulltime'],
    'middle',
    'Thiết kế giao diện sản phẩm số, thực hiện prototype và kiểm thử khả dụng với người dùng.',
    ARRAY['Thiết kế wireframe và prototype', 'Phối hợp với đội sản phẩm', 'Cải thiện trải nghiệm người dùng'],
    ARRAY['Thành thạo Figma', 'Có tư duy UI/UX', 'Biết nghiên cứu người dùng'],
    '[{"name":"Figma","normalized_name":"figma","level":"advanced","category":"design"},{"name":"User Research","normalized_name":"user_research","level":"intermediate","category":"design"},{"name":"UI Design","normalized_name":"ui_design","level":"intermediate","category":"design"}]'::jsonb,
    ARRAY['Figma','FigJam'],
    ARRAY['product_design'],
    3,
    'bachelor',
    '{"level":"bachelor","major":"Thiết kế đồ họa"}'::jsonb,
    ARRAY[]::text[],
    '{"min":18000000,"max":32000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Ngân sách công cụ thiết kế', 'Làm việc hybrid'],
    ARRAY['design','figma','ux'],
    ARRAY['Thiết kế sáng tạo'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000011',
    '99999999-9999-9999-9999-999999999991',
    'Nhân viên Điều phối Logistics',
    'nhan-vien-dieu-phoi-logistics',
    'published',
    'public',
    'Công ty Cảng Xanh',
    'Hải Phòng',
    '100-500',
    'Logistics',
    'logistics_supply_chain',
    'logistics_staff',
    'Vận hành',
    '{"city":"Hải Phòng","country":"Việt Nam","remote_type":"onsite"}'::jsonb,
    ARRAY['fulltime'],
    'junior',
    'Theo dõi vận đơn, phối hợp kho vận và cập nhật tiến độ giao hàng cho khách hàng.',
    ARRAY['Theo dõi lịch giao hàng', 'Làm việc với kho và nhà vận chuyển', 'Cập nhật báo cáo vận hành'],
    ARRAY['Hiểu quy trình logistics', 'Sử dụng Excel tốt', 'Xử lý vấn đề nhanh'],
    '[{"name":"Logistics","normalized_name":"logistics","level":"basic","category":"logistics"},{"name":"Excel","normalized_name":"excel","level":"intermediate","category":"tool"},{"name":"Problem Solving","normalized_name":"problem_solving","level":"basic","category":"soft_skill"}]'::jsonb,
    ARRAY['Excel','WMS'],
    ARRAY['logistics'],
    1,
    'associate',
    '{"level":"associate","major":"Logistics"}'::jsonb,
    ARRAY[]::text[],
    '{"min":12000000,"max":20000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Phụ cấp ăn trưa', 'Đào tạo nghiệp vụ'],
    ARRAY['logistics','supply-chain','excel'],
    ARRAY['Logistics'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000012',
    '99999999-9999-9999-9999-999999999991',
    'Nhân viên Chăm sóc khách hàng',
    'nhan-vien-cham-soc-khach-hang',
    'published',
    'public',
    'Công ty HappyCall Việt Nam',
    'TP. Hồ Chí Minh',
    '100-500',
    'Dịch vụ khách hàng',
    'customer_service',
    'customer_support',
    'Chăm sóc khách hàng',
    '{"city":"TP. Hồ Chí Minh","country":"Việt Nam","remote_type":"onsite"}'::jsonb,
    ARRAY['fulltime'],
    'junior',
    'Tiếp nhận yêu cầu khách hàng, xử lý phản hồi và cập nhật thông tin trên hệ thống CRM.',
    ARRAY['Tiếp nhận cuộc gọi', 'Xử lý yêu cầu khách hàng', 'Ghi nhận phản hồi trên CRM'],
    ARRAY['Giọng nói rõ ràng', 'Kiên nhẫn khi xử lý tình huống', 'Biết dùng CRM là lợi thế'],
    '[{"name":"Customer Service","normalized_name":"customer_service","level":"intermediate","category":"service"},{"name":"Communication","normalized_name":"communication","level":"intermediate","category":"soft_skill"},{"name":"CRM","normalized_name":"crm","level":"basic","category":"tool"}]'::jsonb,
    ARRAY['CRM','Tổng đài'],
    ARRAY['customer_service'],
    1,
    'high_school',
    '{"level":"high_school","major":"Phổ thông"}'::jsonb,
    ARRAY[]::text[],
    '{"min":9000000,"max":15000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Phụ cấp ca', 'Đào tạo quy trình'],
    ARRAY['customer-service','crm','support'],
    ARRAY['Dịch vụ khách hàng'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000013',
    '99999999-9999-9999-9999-999999999991',
    'Quản lý Sản xuất',
    'quan-ly-san-xuat',
    'published',
    'public',
    'Nhà máy Cơ khí Đồng Nai',
    'Đồng Nai',
    '500-1000',
    'Sản xuất',
    'manufacturing',
    'production_worker',
    'Sản xuất',
    '{"city":"Đồng Nai","country":"Việt Nam","remote_type":"onsite"}'::jsonb,
    ARRAY['fulltime'],
    'manager',
    'Quản lý ca sản xuất, theo dõi chất lượng và phối hợp bảo trì thiết bị trong nhà máy.',
    ARRAY['Lập kế hoạch ca sản xuất', 'Theo dõi chất lượng', 'Điều phối nhân sự chuyền'],
    ARRAY['Có kinh nghiệm quản lý sản xuất', 'Hiểu kiểm soát chất lượng', 'Có kỹ năng lãnh đạo'],
    '[{"name":"Manufacturing","normalized_name":"manufacturing","level":"intermediate","category":"operations"},{"name":"Leadership","normalized_name":"leadership","level":"intermediate","category":"soft_skill"},{"name":"Quality Control","normalized_name":"quality_control","level":"basic","category":"operations"}]'::jsonb,
    ARRAY['Excel','ERP'],
    ARRAY['manufacturing'],
    5,
    'associate',
    '{"level":"associate","major":"Cơ khí"}'::jsonb,
    ARRAY[]::text[],
    '{"min":25000000,"max":40000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Phụ cấp ca', 'Thưởng năng suất'],
    ARRAY['manufacturing','production','quality'],
    ARRAY['Sản xuất'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000014',
    '99999999-9999-9999-9999-999999999991',
    'Trợ lý Pháp lý',
    'tro-ly-phap-ly',
    'published',
    'public',
    'Công ty Luật Minh Tâm',
    'Hà Nội',
    '20-50',
    'Pháp lý',
    'legal',
    'legal_staff',
    'Pháp chế',
    '{"city":"Hà Nội","country":"Việt Nam","remote_type":"onsite"}'::jsonb,
    ARRAY['fulltime'],
    'junior',
    'Hỗ trợ rà soát hợp đồng, lưu trữ hồ sơ pháp lý và chuẩn bị tài liệu cho luật sư.',
    ARRAY['Rà soát hợp đồng cơ bản', 'Quản lý hồ sơ pháp lý', 'Chuẩn bị tài liệu họp'],
    ARRAY['Tốt nghiệp ngành luật', 'Cẩn thận với tài liệu', 'Kỹ năng nghiên cứu pháp lý'],
    '[{"name":"Legal Research","normalized_name":"legal_research","level":"basic","category":"legal"},{"name":"Document Management","normalized_name":"document_management","level":"intermediate","category":"administration"},{"name":"Attention to Detail","normalized_name":"attention_to_detail","level":"intermediate","category":"soft_skill"}]'::jsonb,
    ARRAY['Word','Excel'],
    ARRAY['legal'],
    1,
    'bachelor',
    '{"level":"bachelor","major":"Luật"}'::jsonb,
    ARRAY[]::text[],
    '{"min":10000000,"max":18000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Đào tạo nghiệp vụ', 'Bảo hiểm'],
    ARRAY['legal','contract','document'],
    ARRAY['Pháp lý'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000015',
    '99999999-9999-9999-9999-999999999991',
    'Nhân viên Bán lẻ',
    'nhan-vien-ban-le',
    'published',
    'public',
    'Chuỗi Cửa hàng Sao Mai',
    'TP. Hồ Chí Minh',
    '500-1000',
    'Bán lẻ',
    'retail',
    'retail_staff',
    'Cửa hàng',
    '{"city":"TP. Hồ Chí Minh","country":"Việt Nam","remote_type":"onsite"}'::jsonb,
    ARRAY['fulltime'],
    'fresher',
    'Tư vấn sản phẩm tại cửa hàng, hỗ trợ thanh toán và duy trì trưng bày hàng hóa.',
    ARRAY['Tư vấn khách hàng', 'Sắp xếp quầy kệ', 'Hỗ trợ kiểm kê hàng hóa'],
    ARRAY['Thái độ phục vụ tốt', 'Có thể làm ca xoay', 'Ưu tiên có kinh nghiệm bán lẻ'],
    '[{"name":"Sales","normalized_name":"sales","level":"basic","category":"sales"},{"name":"Communication","normalized_name":"communication","level":"intermediate","category":"soft_skill"},{"name":"Customer Relationship","normalized_name":"customer_relationship","level":"basic","category":"service"}]'::jsonb,
    ARRAY['POS','CRM'],
    ARRAY['retail'],
    0,
    'high_school',
    '{"level":"high_school","major":"Phổ thông"}'::jsonb,
    ARRAY[]::text[],
    '{"min":8000000,"max":25000000,"currency":"VND","period":"month","note":"Lương cứng cộng hoa hồng"}'::jsonb,
    ARRAY['Hoa hồng', 'Đào tạo sản phẩm'],
    ARRAY['retail','sales','store'],
    ARRAY['Bán lẻ'],
    false,
    false
),
(
    '91000000-0000-0000-0000-000000000016',
    '99999999-9999-9999-9999-999999999991',
    'Lễ tân Khách sạn',
    'le-tan-khach-san',
    'published',
    'public',
    'Khách sạn Biển Xanh',
    'Đà Nẵng',
    '50-100',
    'Khách sạn - Du lịch',
    'hospitality_tourism',
    'hotel_staff',
    'Tiền sảnh',
    '{"city":"Đà Nẵng","country":"Việt Nam","remote_type":"onsite"}'::jsonb,
    ARRAY['fulltime'],
    'junior',
    'Đón tiếp khách lưu trú, xử lý đặt phòng và hỗ trợ yêu cầu trong thời gian khách ở khách sạn.',
    ARRAY['Làm thủ tục nhận phòng', 'Xử lý đặt phòng', 'Hỗ trợ thông tin du lịch'],
    ARRAY['Giao tiếp tiếng Anh cơ bản', 'Thái độ phục vụ tốt', 'Có kinh nghiệm khách sạn là lợi thế'],
    '[{"name":"Hospitality","normalized_name":"hospitality","level":"basic","category":"hospitality"},{"name":"English","normalized_name":"english","level":"intermediate","category":"language"},{"name":"Customer Service","normalized_name":"customer_service","level":"intermediate","category":"service"}]'::jsonb,
    ARRAY['PMS','Excel'],
    ARRAY['hospitality'],
    1,
    'high_school',
    '{"level":"high_school","major":"Du lịch"}'::jsonb,
    ARRAY[]::text[],
    '{"min":9000000,"max":15000000,"currency":"VND","period":"month"}'::jsonb,
    ARRAY['Phụ cấp ca', 'Bữa ăn nhân viên'],
    ARRAY['hospitality','hotel','front-office'],
    ARRAY['Khách sạn - Du lịch'],
    false,
    false
)
ON CONFLICT (id) DO UPDATE
SET created_by = EXCLUDED.created_by,
    title = EXCLUDED.title,
    slug = EXCLUDED.slug,
    status = 'published',
    visibility = 'public',
    company_name = EXCLUDED.company_name,
    company_location = EXCLUDED.company_location,
    company_size = EXCLUDED.company_size,
    company_industry = EXCLUDED.company_industry,
    industry = EXCLUDED.industry,
    occupation_group = EXCLUDED.occupation_group,
    department = EXCLUDED.department,
    location = EXCLUDED.location,
    employment_type = EXCLUDED.employment_type,
    seniority = EXCLUDED.seniority,
    description = EXCLUDED.description,
    responsibilities = EXCLUDED.responsibilities,
    requirements = EXCLUDED.requirements,
    skills = EXCLUDED.skills,
    tools_and_technologies = EXCLUDED.tools_and_technologies,
    domain_knowledge = EXCLUDED.domain_knowledge,
    experience_years = EXCLUDED.experience_years,
    education_level = EXCLUDED.education_level,
    required_education = EXCLUDED.required_education,
    required_certifications = EXCLUDED.required_certifications,
    salary = EXCLUDED.salary,
    benefits = EXCLUDED.benefits,
    tags = EXCLUDED.tags,
    categories = EXCLUDED.categories,
    remote = EXCLUDED.remote,
    archived = false;

INSERT INTO cvs (
    id,
    created_by,
    fullname,
    email,
    phone,
    location,
    headline,
    summary,
    industry,
    occupation_group,
    career_level,
    years_of_experience,
    target_role,
    employment_type,
    availability,
    skills,
    tools_and_technologies,
    domain_knowledge,
    experiences,
    education,
    projects,
    certifications,
    languages,
    tags,
    status,
    visibility,
    file,
    archived
)
VALUES
(
    '92000000-0000-0000-0000-000000000001',
    '99999999-9999-9999-9999-999999999992',
    'Nguyễn Văn An',
    'candidate.backend@example.com',
    '0900000001',
    '{"city":"Hà Nội","country":"Việt Nam","remote_type":"hybrid"}'::jsonb,
    'Lập trình viên Backend Python',
    'Có kinh nghiệm xây dựng API với FastAPI, PostgreSQL và triển khai dịch vụ backend.',
    'information_technology',
    'software_engineering',
    'middle',
    3,
    'Lập trình viên Backend Python',
    ARRAY['fulltime'],
    'within_1_month',
    '[{"name":"Python","normalized_name":"python","level":"advanced","category":"technical","years":3},{"name":"FastAPI","normalized_name":"fastapi","level":"intermediate","category":"technical","years":2},{"name":"PostgreSQL","normalized_name":"postgresql","level":"intermediate","category":"technical","years":3}]'::jsonb,
    ARRAY['FastAPI','PostgreSQL','Docker'],
    ARRAY['ecommerce','recruitment'],
    '[{"title":"Lập trình viên Backend","company":"Công ty Phần mềm Việt","responsibilities":["Phát triển REST API","Tối ưu truy vấn PostgreSQL"],"achievements":["Rút ngắn thời gian phản hồi API"]}]'::jsonb,
    '[{"degree":"Cử nhân","level":"bachelor","major":"Công nghệ thông tin","school":"Đại học Bách khoa"}]'::jsonb,
    '[{"name":"Hệ thống quản lý tuyển dụng","description":"Xây dựng API quản lý hồ sơ ứng viên","techStack":["Python","FastAPI","PostgreSQL"]}]'::jsonb,
    '[]'::jsonb,
    '[{"name":"Tiếng Anh","level":"intermediate"}]'::jsonb,
    ARRAY['python','backend','fastapi'],
    'published',
    'public',
    '{}'::jsonb,
    false
),
(
    '92000000-0000-0000-0000-000000000002',
    '99999999-9999-9999-9999-999999999992',
    'Trần Thị Bình',
    'candidate.marketing@example.com',
    '0900000002',
    '{"city":"TP. Hồ Chí Minh","country":"Việt Nam","remote_type":"onsite"}'::jsonb,
    'Chuyên viên Digital Marketing',
    'Có kinh nghiệm lập kế hoạch chiến dịch, quản lý nội dung và báo cáo hiệu quả quảng cáo.',
    'marketing',
    'digital_marketing',
    'junior',
    2,
    'Chuyên viên Digital Marketing',
    ARRAY['fulltime'],
    'immediately',
    '[{"name":"Digital Marketing","normalized_name":"digital_marketing","level":"intermediate","category":"marketing","years":2},{"name":"Content Planning","normalized_name":"content_planning","level":"intermediate","category":"marketing","years":2},{"name":"Excel","normalized_name":"excel","level":"basic","category":"tool","years":2}]'::jsonb,
    ARRAY['Meta Ads','Google Analytics','Excel'],
    ARRAY['ecommerce'],
    '[{"title":"Nhân viên Marketing","company":"Thương hiệu Bán lẻ Việt","responsibilities":["Lập kế hoạch chiến dịch","Theo dõi hiệu quả kênh"],"achievements":["Tăng số lượng khách hàng tiềm năng"]}]'::jsonb,
    '[{"degree":"Cử nhân","level":"bachelor","major":"Marketing","school":"Đại học Kinh tế"}]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[{"name":"Tiếng Anh","level":"intermediate"}]'::jsonb,
    ARRAY['marketing','content','campaign'],
    'published',
    'public',
    '{}'::jsonb,
    false
),
(
    '92000000-0000-0000-0000-000000000003',
    '99999999-9999-9999-9999-999999999992',
    'Lê Minh Châu',
    'candidate.accounting@example.com',
    '0900000003',
    '{"city":"Hà Nội","country":"Việt Nam","remote_type":"onsite"}'::jsonb,
    'Kế toán tổng hợp',
    'Có kinh nghiệm xử lý hóa đơn, đối chiếu công nợ và lập báo cáo tài chính.',
    'accounting_finance',
    'accountant',
    'middle',
    4,
    'Kế toán tổng hợp',
    ARRAY['fulltime'],
    'within_1_week',
    '[{"name":"Kế toán","normalized_name":"accounting","level":"intermediate","category":"finance","years":3},{"name":"Excel","normalized_name":"excel","level":"advanced","category":"tool","years":4},{"name":"Báo cáo tài chính","normalized_name":"financial_reporting","level":"intermediate","category":"finance","years":2}]'::jsonb,
    ARRAY['Excel','MISA'],
    ARRAY['accounting','tax'],
    '[{"title":"Kế toán viên","company":"Công ty Thương mại An Phát","responsibilities":["Ghi nhận nghiệp vụ","Đối chiếu hóa đơn"],"achievements":["Giảm lỗi báo cáo tháng"]}]'::jsonb,
    '[{"degree":"Cử nhân","level":"bachelor","major":"Kế toán","school":"Đại học Tài chính"}]'::jsonb,
    '[]'::jsonb,
    '[{"name":"Chứng chỉ kế toán trưởng","issuer":"Viện Đào tạo Kế toán"}]'::jsonb,
    '[{"name":"Tiếng Anh","level":"basic"}]'::jsonb,
    ARRAY['accounting','excel','finance'],
    'published',
    'public',
    '{}'::jsonb,
    false
),
(
    '92000000-0000-0000-0000-000000000004',
    '99999999-9999-9999-9999-999999999992',
    'Phạm Quốc Dũng',
    'candidate.logistics@example.com',
    '0900000004',
    '{"city":"Hải Phòng","country":"Việt Nam","remote_type":"onsite"}'::jsonb,
    'Nhân viên Điều phối Logistics',
    'Có kinh nghiệm theo dõi vận đơn, phối hợp kho vận và cập nhật tiến độ giao hàng.',
    'logistics_supply_chain',
    'logistics_staff',
    'junior',
    2,
    'Nhân viên Điều phối Logistics',
    ARRAY['fulltime'],
    'immediately',
    '[{"name":"Logistics","normalized_name":"logistics","level":"intermediate","category":"logistics","years":2},{"name":"Excel","normalized_name":"excel","level":"intermediate","category":"tool","years":3},{"name":"Problem Solving","normalized_name":"problem_solving","level":"basic","category":"soft_skill","years":2}]'::jsonb,
    ARRAY['Excel','WMS'],
    ARRAY['logistics'],
    '[{"title":"Nhân viên Logistics","company":"Nhà vận hành Kho Việt","responsibilities":["Theo dõi lô hàng","Cập nhật dữ liệu giao nhận"],"achievements":["Cải thiện độ chính xác điều phối"]}]'::jsonb,
    '[{"degree":"Cao đẳng","level":"associate","major":"Logistics","school":"Cao đẳng Giao thông"}]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[{"name":"Tiếng Anh","level":"basic"}]'::jsonb,
    ARRAY['logistics','supply-chain','excel'],
    'published',
    'public',
    '{}'::jsonb,
    false
),
(
    '92000000-0000-0000-0000-000000000005',
    '99999999-9999-9999-9999-999999999992',
    'Hoàng Thị Hạnh',
    'candidate.design@example.com',
    '0900000005',
    '{"city":"Hà Nội","country":"Việt Nam","remote_type":"hybrid"}'::jsonb,
    'Nhà thiết kế UI/UX',
    'Có kinh nghiệm thiết kế giao diện sản phẩm số, prototype và nghiên cứu người dùng.',
    'design_creative',
    'ui_ux_designer',
    'middle',
    3,
    'Nhà thiết kế UI/UX',
    ARRAY['fulltime'],
    'negotiable',
    '[{"name":"Figma","normalized_name":"figma","level":"advanced","category":"design","years":3},{"name":"User Research","normalized_name":"user_research","level":"intermediate","category":"design","years":2},{"name":"UI Design","normalized_name":"ui_design","level":"intermediate","category":"design","years":3}]'::jsonb,
    ARRAY['Figma','FigJam'],
    ARRAY['product_design'],
    '[{"title":"Product Designer","company":"Studio Sáng Tạo","responsibilities":["Thiết kế prototype","Thực hiện đánh giá khả dụng"],"achievements":["Cải thiện tỷ lệ hoàn thành tác vụ"]}]'::jsonb,
    '[{"degree":"Cử nhân","level":"bachelor","major":"Thiết kế đồ họa","school":"Đại học Mỹ thuật"}]'::jsonb,
    '[{"name":"Thiết kế lại ứng dụng di động","description":"Cải thiện luồng onboarding","techStack":["Figma"]}]'::jsonb,
    '[]'::jsonb,
    '[{"name":"Tiếng Anh","level":"intermediate"}]'::jsonb,
    ARRAY['design','figma','ux'],
    'published',
    'public',
    '{}'::jsonb,
    false
),
(
    '92000000-0000-0000-0000-000000000006',
    '99999999-9999-9999-9999-999999999992',
    'Đỗ Văn Phúc',
    'candidate.sales@example.com',
    '0900000006',
    '{"city":"Đà Nẵng","country":"Việt Nam","remote_type":"onsite"}'::jsonb,
    'Nhân viên Kinh doanh B2B',
    'Có kinh nghiệm tìm kiếm khách hàng doanh nghiệp, chuẩn bị báo giá và chăm sóc khách hàng.',
    'sales',
    'sales_executive',
    'junior',
    2,
    'Nhân viên Kinh doanh B2B',
    ARRAY['fulltime'],
    'immediately',
    '[{"name":"Sales","normalized_name":"sales","level":"intermediate","category":"sales","years":2},{"name":"Communication","normalized_name":"communication","level":"intermediate","category":"soft_skill","years":3},{"name":"CRM","normalized_name":"crm","level":"basic","category":"tool","years":1}]'::jsonb,
    ARRAY['CRM','Excel'],
    ARRAY['b2b_sales'],
    '[{"title":"Nhân viên kinh doanh","company":"Công ty Phân phối Miền Trung","responsibilities":["Tìm kiếm khách hàng","Chuẩn bị báo giá"],"achievements":["Vượt chỉ tiêu tháng"]}]'::jsonb,
    '[{"degree":"Cao đẳng","level":"associate","major":"Quản trị kinh doanh","school":"Cao đẳng Kinh tế"}]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[{"name":"Tiếng Anh","level":"basic"}]'::jsonb,
    ARRAY['sales','b2b','crm'],
    'published',
    'public',
    '{}'::jsonb,
    false
),
(
    '92000000-0000-0000-0000-000000000007',
    '99999999-9999-9999-9999-999999999992',
    'Vũ Thị Giang',
    'candidate.hr@example.com',
    '0900000007',
    '{"city":"Hà Nội","country":"Việt Nam","remote_type":"hybrid"}'::jsonb,
    'Chuyên viên Tuyển dụng',
    'Có kinh nghiệm tìm kiếm ứng viên, phỏng vấn sơ bộ và điều phối quy trình tuyển dụng.',
    'human_resources',
    'hr_recruitment',
    'middle',
    3,
    'Chuyên viên Tuyển dụng',
    ARRAY['fulltime'],
    'within_1_month',
    '[{"name":"Recruitment","normalized_name":"recruitment","level":"intermediate","category":"human_resources","years":3},{"name":"Interviewing","normalized_name":"interviewing","level":"intermediate","category":"human_resources","years":2},{"name":"Communication","normalized_name":"communication","level":"intermediate","category":"soft_skill","years":3}]'::jsonb,
    ARRAY['LinkedIn','Google Sheets'],
    ARRAY['recruitment'],
    '[{"title":"Chuyên viên tuyển dụng","company":"Dịch vụ Nhân sự Việt","responsibilities":["Tìm nguồn ứng viên","Điều phối phỏng vấn"],"achievements":["Giảm thời gian tuyển dụng"]}]'::jsonb,
    '[{"degree":"Cử nhân","level":"bachelor","major":"Quản trị nhân lực","school":"Đại học Lao động Xã hội"}]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[{"name":"Tiếng Anh","level":"intermediate"}]'::jsonb,
    ARRAY['hr','recruitment','people'],
    'published',
    'public',
    '{}'::jsonb,
    false
),
(
    '92000000-0000-0000-0000-000000000008',
    '99999999-9999-9999-9999-999999999992',
    'Bùi Minh Hải',
    'candidate.hospitality@example.com',
    '0900000008',
    '{"city":"Đà Nẵng","country":"Việt Nam","remote_type":"onsite"}'::jsonb,
    'Lễ tân Khách sạn',
    'Có kinh nghiệm đón tiếp khách, xử lý đặt phòng và giao tiếp tiếng Anh trong môi trường khách sạn.',
    'hospitality_tourism',
    'hotel_staff',
    'junior',
    2,
    'Lễ tân Khách sạn',
    ARRAY['fulltime'],
    'immediately',
    '[{"name":"Hospitality","normalized_name":"hospitality","level":"intermediate","category":"hospitality","years":2},{"name":"English","normalized_name":"english","level":"intermediate","category":"language","years":3},{"name":"Customer Service","normalized_name":"customer_service","level":"intermediate","category":"service","years":3}]'::jsonb,
    ARRAY['PMS','Excel'],
    ARRAY['hospitality'],
    '[{"title":"Nhân viên lễ tân","company":"Khách sạn Biển Xanh","responsibilities":["Làm thủ tục nhận phòng","Xử lý đặt phòng"],"achievements":["Cải thiện mức hài lòng của khách"]}]'::jsonb,
    '[{"degree":"Trung học phổ thông","level":"high_school","major":"Phổ thông","school":"Trường THPT Đà Nẵng"}]'::jsonb,
    '[]'::jsonb,
    '[]'::jsonb,
    '[{"name":"Tiếng Anh","level":"intermediate"}]'::jsonb,
    ARRAY['hospitality','hotel','front-office'],
    'published',
    'public',
    '{}'::jsonb,
    false
)
ON CONFLICT (id) DO UPDATE
SET created_by = EXCLUDED.created_by,
    fullname = EXCLUDED.fullname,
    email = EXCLUDED.email,
    phone = EXCLUDED.phone,
    location = EXCLUDED.location,
    headline = EXCLUDED.headline,
    summary = EXCLUDED.summary,
    industry = EXCLUDED.industry,
    occupation_group = EXCLUDED.occupation_group,
    career_level = EXCLUDED.career_level,
    years_of_experience = EXCLUDED.years_of_experience,
    target_role = EXCLUDED.target_role,
    employment_type = EXCLUDED.employment_type,
    availability = EXCLUDED.availability,
    skills = EXCLUDED.skills,
    tools_and_technologies = EXCLUDED.tools_and_technologies,
    domain_knowledge = EXCLUDED.domain_knowledge,
    experiences = EXCLUDED.experiences,
    education = EXCLUDED.education,
    projects = EXCLUDED.projects,
    certifications = EXCLUDED.certifications,
    languages = EXCLUDED.languages,
    tags = EXCLUDED.tags,
    status = 'published',
    visibility = 'public',
    file = EXCLUDED.file,
    archived = false;
